project_id = "ovzijmqrnsgcmryinkfa"

[db.seed]
enabled = true
sql_paths = ['./seeds/default_feature_flags.sql', './seed.sql', './seeds/default_realtime_signals.sql']

[functions.manage-user]
verify_jwt = true

[functions.claim-account]
verify_jwt = true

[functions.register-account]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.send-prediction-reminders]
verify_jwt = true

[functions.calendar-feed]
verify_jwt = false