-- Canonical product seed for fresh/local installations only.
-- Do not copy club, user, player, match or historical production data here.
-- The production-only QA badge `test_qa_badge` is intentionally excluded.

insert into public.badges (
  code, name, description, emoji, family, auto, metric, threshold,
  sort_order, kind, category, image_url, color, has_star, standalone, secret
) values
('matches_played_season__15','Habitué','Participer à 15 matchs au cours d''une même saison.','📅','joueur',true,'matches_played_season',15,100,'tier','joueur_saison',null,'#6E7A86',false,false,false),
('matches_played_season__20','Assidu','Participer à 20 matchs au cours d''une même saison.','📅','joueur',true,'matches_played_season',20,101,'tier','joueur_saison',null,'#B87333',false,false,false),
('matches_played_season__25','Pilier','Participer à 25 matchs au cours d''une même saison.','📅','joueur',true,'matches_played_season',25,102,'tier','joueur_saison',null,'#C4CBD4',false,false,false),
('matches_played_season__30','Incontournable','Participer à 30 matchs au cours d''une même saison.','📅','joueur',true,'matches_played_season',30,103,'tier','joueur_saison',null,'#E3B23C',true,false,false),
('matches_played__150','Fidèle','Atteindre 150 matchs joués avec le club.','📅','joueur',true,'matches_played',150,104,'tier','joueur_all_time',null,'#4FA9E8',false,false,false),
('matches_played__200','Vétéran','Atteindre 200 matchs joués avec le club.','📅','joueur',true,'matches_played',200,105,'tier','joueur_all_time',null,'#1E3A8A',false,false,false),
('matches_played__250','Cadre du club','Atteindre 250 matchs joués avec le club.','📅','joueur',true,'matches_played',250,106,'tier','joueur_all_time',null,'#7C3AED',false,false,false),
('matches_played__300','Légende du club','Atteindre 300 matchs joués avec le club.','📅','joueur',true,'matches_played',300,107,'tier','joueur_all_time',null,'#1C1C24',true,false,false),
('goals_season__5','Première gâchette','Marquer 5 buts au cours d''une même saison.','⚽','joueur',true,'goals_season',5,110,'tier','joueur_saison',null,'#6E7A86',false,false,false),
('goals_season__10','Finisseur','Marquer 10 buts au cours d''une même saison.','⚽','joueur',true,'goals_season',10,111,'tier','joueur_saison',null,'#B87333',false,false,false),
('goals_season__20','Artilleur','Marquer 20 buts au cours d''une même saison.','⚽','joueur',true,'goals_season',20,112,'tier','joueur_saison',null,'#C4CBD4',false,false,false),
('goals_season__30','Goleador','Marquer 30 buts au cours d''une même saison.','⚽','joueur',true,'goals_season',30,113,'tier','joueur_saison',null,'#E3B23C',true,false,false),
('goals__25','Buteur confirmé','Atteindre 25 buts marqués avec le club.','⚽','joueur',true,'goals',25,114,'tier','joueur_all_time',null,'#4FA9E8',false,false,false),
('goals__50','Canonnier','Atteindre 50 buts marqués avec le club.','⚽','joueur',true,'goals',50,115,'tier','joueur_all_time',null,'#1E3A8A',false,false,false),
('goals__75','Chasseur de records','Atteindre 75 buts marqués avec le club.','⚽','joueur',true,'goals',75,116,'tier','joueur_all_time',null,'#7C3AED',false,false,false),
('goals__100','Centurion','Atteindre la barre mythique des 100 buts avec le club.','⚽','joueur',true,'goals',100,117,'tier','joueur_all_time',null,'#1C1C24',true,false,false),
('wins_season__10','Compétiteur','Remporter 10 matchs au cours d''une même saison.','🏆','joueur',true,'wins_season',10,120,'tier','joueur_saison',null,'#6E7A86',false,false,false),
('wins_season__15','Gagnant','Remporter 15 matchs au cours d''une même saison.','🏆','joueur',true,'wins_season',15,121,'tier','joueur_saison',null,'#B87333',false,false,false),
('wins_season__20','Serial winner','Remporter 20 matchs au cours d''une même saison.','🏆','joueur',true,'wins_season',20,122,'tier','joueur_saison',null,'#C4CBD4',false,false,false),
('wins_season__25','Invincible','Remporter 25 matchs au cours d''une même saison.','🏆','joueur',true,'wins_season',25,123,'tier','joueur_saison',null,'#E3B23C',true,false,false),
('wins__50','Habitué de la victoire','Atteindre 50 victoires avec le club.','🏆','joueur',true,'wins',50,124,'tier','joueur_all_time',null,'#4FA9E8',false,false,false),
('wins__100','Centurion victorieux','Atteindre 100 victoires avec le club.','🏆','joueur',true,'wins',100,125,'tier','joueur_all_time',null,'#1E3A8A',false,false,false),
('wins__150','Maître de la gagne','Atteindre 150 victoires avec le club.','🏆','joueur',true,'wins',150,126,'tier','joueur_all_time',null,'#7C3AED',false,false,false),
('wins__200','Légende victorieuse','Atteindre 200 victoires avec le club.','🏆','joueur',true,'wins',200,127,'tier','joueur_all_time',null,'#1C1C24',true,false,false),
('clean_sheets_season__3','Premier verrou','Terminer 3 matchs sans encaisser de but au cours d''une même saison.','🧱','joueur',true,'clean_sheets_season',3,130,'tier','joueur_saison',null,'#6E7A86',false,false,false),
('clean_sheets_season__5','Dernier rempart','Terminer 5 matchs sans encaisser de but au cours d''une même saison.','🧱','joueur',true,'clean_sheets_season',5,131,'tier','joueur_saison',null,'#B87333',false,false,false),
('clean_sheets_season__7','Muraille','Terminer 7 matchs sans encaisser de but au cours d''une même saison.','🧱','joueur',true,'clean_sheets_season',7,132,'tier','joueur_saison',null,'#C4CBD4',false,false,false),
('clean_sheets_season__10','Forteresse imprenable','Terminer 10 matchs sans encaisser de but au cours d''une même saison.','🧱','joueur',true,'clean_sheets_season',10,133,'tier','joueur_saison',null,'#E3B23C',true,false,false),
('clean_sheets__15','Verrou confirmé','Atteindre 15 matchs sans encaisser de but avec le club.','🧱','joueur',true,'clean_sheets',15,134,'tier','joueur_all_time',null,'#4FA9E8',false,false,false),
('clean_sheets__25','Gardien du temple','Atteindre 25 matchs sans encaisser de but avec le club.','🧱','joueur',true,'clean_sheets',25,135,'tier','joueur_all_time',null,'#1E3A8A',false,false,false),
('clean_sheets__50','Mur infranchissable','Atteindre 50 matchs sans encaisser de but avec le club.','🧱','joueur',true,'clean_sheets',50,136,'tier','joueur_all_time',null,'#7C3AED',false,false,false),
('clean_sheets__100','Maître des cages','Atteindre 100 matchs sans encaisser de but avec le club.','🧱','joueur',true,'clean_sheets',100,137,'tier','joueur_all_time',null,'#1C1C24',true,false,false),
('mvp__10','Homme fort','Obtenir 10 distinctions d''Homme du match avec le club.','👑','joueur',true,'mvp',10,150,'tier','joueur_all_time',null,'#4FA9E8',false,false,false),
('mvp__20','Joueur décisif','Obtenir 20 distinctions d''Homme du match avec le club.','👑','joueur',true,'mvp',20,151,'tier','joueur_all_time',null,'#1E3A8A',false,false,false),
('mvp__30','Roi du match','Obtenir 30 distinctions d''Homme du match avec le club.','👑','joueur',true,'mvp',30,152,'tier','joueur_all_time',null,'#7C3AED',false,false,false),
('mvp__50','Mobutu','Obtenir 50 distinctions d''Homme du match avec le club.','👑','joueur',true,'mvp',50,153,'tier','joueur_all_time',null,'#1C1C24',true,false,false),
('max_match_goals__3','Triplé','Marquer trois buts au cours d''un même match.','🎩','joueur',true,'max_match_goals',3,160,'tier','joueur_all_time',null,'#F1706E',false,true,false),
('max_match_goals__4','Quadruplé','Marquer quatre buts au cours d''un même match.','🃏','joueur',true,'max_match_goals',4,161,'tier','joueur_all_time',null,'#E23B36',false,true,false),
('max_match_goals__5','Quintuplé','Marquer cinq buts au cours d''un même match.','🖐️','joueur',true,'max_match_goals',5,162,'tier','joueur_all_time',null,'#9E1B1B',false,true,false),
('title_most_present__1','Monsieur Présent','Terminer une saison en étant le joueur ayant participé au plus grand nombre de matchs.','🙋','joueur',true,'title_most_present',1,191,'tier','palmares',null,'#5FC9D9',true,false,false),
('title_top_scorer__1','Soulier d''or','Terminer une saison en étant le joueur ayant marqué le plus grand nombre de buts.','🥇','joueur',true,'title_top_scorer',1,192,'tier','palmares',null,'#5FC9D9',true,false,false),
('title_best_winrate__1','Monsieur Victoire','Terminer une saison avec le meilleur taux de victoire parmi les joueurs éligibles.','📈','joueur',true,'title_best_winrate',1,193,'tier','palmares',null,'#5FC9D9',true,false,false),
('title_mvp_king__1','Ballon d''or','Terminer une saison en étant le joueur ayant obtenu le plus de distinctions d''Homme du match.','🌟','joueur',true,'title_mvp_king',1,194,'tier','palmares',null,'#5FC9D9',true,false,false),
('title_best_pred_player__1','L''Analyste','Terminer une saison avec le meilleur total de points sur les pronostics liés aux statistiques des joueurs.','📊','pronostiqueur',true,'title_best_pred_player',1,200,'tier','palmares',null,'#5FC9D9',true,false,false),
('title_best_pred_match__1','Le Visionnaire','Terminer une saison avec le meilleur total de points sur les pronostics de résultats et de scores des matchs.','🔮','pronostiqueur',true,'title_best_pred_match',1,201,'tier','palmares',null,'#5FC9D9',true,false,false),
('title_best_pred_overall__1','Le Cerveau','Terminer une saison avec le meilleur total cumulé sur l''ensemble des catégories de pronostics.','🧠','pronostiqueur',true,'title_best_pred_overall',1,202,'tier','palmares',null,'#5FC9D9',true,false,false),
('bet_against_grinta__1','Traître','Tu as parié contre l’AS Grinta sur un match… et il est passé. Honte à toi.','🐍','pronostiqueur',true,'bet_against_grinta',1,900,'tier','pronos_all_time',null,'#F97316',false,true,true),
('exploit_remplace_gardien','Gardien d''un soir','Prendre la place du gardien pendant un match alors que ce n''est pas son poste habituel.','🧤','joueur',false,null,null,900,'custom','faits_de_jeu',null,'#F2811D',false,false,false),
('exploit_penalty_provoque','Le Boucher','Commettre une faute entraînant un penalty pour l''équipe adverse.','🔪','joueur',false,null,null,902,'custom','faits_de_jeu',null,'#F2811D',false,false,false),
('exploit_penalty_subi','Le Plongeur','Subir une faute dans la surface permettant à son équipe d''obtenir un penalty.','🤿','joueur',false,null,null,903,'custom','faits_de_jeu',null,'#F2811D',false,false,false),
('exploit_penalty_arrete','Goalkeeper','Empêcher l''adversaire de marquer en arrêtant un penalty.','🧤','joueur',false,null,null,904,'custom','faits_de_jeu',null,'#F2811D',false,false,false),
('exploit_but_vainqueur_tardif','Clutch','Marquer dans les dernières minutes le but qui offre définitivement la victoire à son équipe.','🥵','joueur',false,null,null,905,'custom','faits_de_jeu',null,'#F2811D',false,false,false),
('exploit_csc','La Boulette','Envoyer involontairement le ballon dans les cages de sa propre équipe.','🫣','joueur',false,null,null,906,'custom','faits_de_jeu',null,'#F2811D',false,false,false),
('role_president','El Presidente','Exercer officiellement la fonction de président du club.','🤵','joueur',false,null,null,909,'custom','palmares',null,'#1C1C24',false,false,false),
('role_coach','Coach','Exercer officiellement la fonction de coach du club.','👨‍🦲','joueur',false,null,null,910,'custom','palmares',null,'#1C1C24',false,false,false)
on conflict (code) do nothing;