-- Optional sports-management module: workflows, permanent participants and availability.
-- Additive and inert while private.app_feature_flags.sports_management is false.

create type public.sport_availability_state as enum ('pending', 'open', 'closed');
create type public.sport_composition_state as enum ('none', 'draft', 'published', 'updated', 'closed');
create type public.sport_presence_state as enum ('pending', 'confirmed');
create type public.sport_vote_state as enum ('unavailable', 'draft', 'open', 'closed', 'cancelled');
create type public.sport_availability_status as enum ('no_response', 'available', 'absent', 'not_applicable');
create type public.sport_selection_status as enum ('undecided', 'starter', 'substitute', 'not_selected');
create type public.sport_final_presence_status as enum ('pending', 'present', 'actual_absent');
create table public.match_sport_workflows (
  match_id uuid primary key references public.matches(id) on delete restrict,
  availability_state public.sport_availability_state not null default 'pending',
  availability_opens_at timestamptz not null,
  availability_opened_at timestamptz,
  composition_state public.sport_composition_state not null default 'none',
  composition_version integer not null default 0 check (composition_version >= 0),
  squad_size_limit smallint not null default 14 check (squad_size_limit between 1 and 30),
  presence_state public.sport_presence_state not null default 'pending',
  vote_state public.sport_vote_state not null default 'unavailable',
  created_by uuid not null references public.profiles(id) on delete restrict,
  updated_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.match_sport_workflows is
  'Per-match state machine for the optional sports-management module.';
comment on column public.match_sport_workflows.availability_opens_at is
  'Absolute opening instant derived from matches.kickoff_at and server configuration.';
comment on column public.match_sport_workflows.squad_size_limit is
  'Default 14; later staff workflows may override it per match with audit.';
create table public.match_sport_participants (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.match_sport_workflows(match_id) on delete restrict,
  season_player_id uuid not null references public.season_players(id) on delete restrict,
  is_eligible boolean not null default true,
  availability_status public.sport_availability_status not null default 'no_response',
  availability_comment_private text,
  availability_updated_at timestamptz,
  availability_updated_by uuid references public.profiles(id) on delete set null,
  selection_status public.sport_selection_status not null default 'undecided',
  selection_updated_at timestamptz,
  selection_updated_by uuid references public.profiles(id) on delete set null,
  final_presence_status public.sport_final_presence_status not null default 'pending',
  final_presence_confirmed_at timestamptz,
  final_presence_confirmed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, season_player_id),
  unique (id, match_id),
  check (
    availability_comment_private is null
    or char_length(availability_comment_private) <= 500
  ),
  check (
    availability_comment_private is null
    or availability_status = 'absent'
  )
);
comment on table public.match_sport_participants is
  'Permanent roster participants. Guest identities are introduced by a later isolated migration.';
comment on column public.match_sport_participants.availability_comment_private is
  'Private absence comment visible only to its player and active administrators.';
comment on column public.match_sport_participants.final_presence_status is
  'Actual attendance, intentionally independent from availability and selection.';
create table public.match_sport_participant_events (
  id bigint generated by default as identity primary key,
  participant_id uuid not null,
  match_id uuid not null,
  event_type text not null check (
    event_type ~ '^[a-z][a-z0-9_]*$' and char_length(event_type) <= 64
  ),
  old_value jsonb check (old_value is null or jsonb_typeof(old_value) = 'object'),
  new_value jsonb check (new_value is null or jsonb_typeof(new_value) = 'object'),
  actor_profile_id uuid references public.profiles(id) on delete set null,
  actor_kind text not null check (actor_kind in ('player', 'staff', 'system')),
  created_at timestamptz not null default now(),
  foreign key (participant_id, match_id)
    references public.match_sport_participants(id, match_id) on delete restrict
);
comment on table public.match_sport_participant_events is
  'Append-only history for availability responses and later staff decisions.';
create table private.sport_admin_audit_log (
  id bigint generated by default as identity primary key,
  match_id uuid references public.matches(id) on delete set null,
  action text not null check (
    action ~ '^[a-z][a-z0-9_]*$' and char_length(action) <= 96
  ),
  actor_profile_id uuid not null references public.profiles(id) on delete restrict,
  reason text check (reason is null or char_length(reason) <= 500),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);
comment on table private.sport_admin_audit_log is
  'Private append-only audit trail for privileged sports-management actions.';
create index match_sport_workflows_availability_due_idx
  on public.match_sport_workflows (availability_state, availability_opens_at);
create index match_sport_participants_match_status_idx
  on public.match_sport_participants (match_id, availability_status)
  where is_eligible;
create index match_sport_participants_season_player_idx
  on public.match_sport_participants (season_player_id);
create index match_sport_participant_events_timeline_idx
  on public.match_sport_participant_events (participant_id, created_at desc);
create index if not exists season_players_profile_id_idx
  on public.season_players (profile_id)
  where profile_id is not null;
create index sport_admin_audit_log_match_timeline_idx
  on private.sport_admin_audit_log (match_id, created_at desc);
alter table public.match_sport_workflows enable row level security;
alter table public.match_sport_participants enable row level security;
alter table public.match_sport_participant_events enable row level security;
alter table private.sport_admin_audit_log enable row level security;
revoke all on table public.match_sport_workflows from public, anon, authenticated;
revoke all on table public.match_sport_participants from public, anon, authenticated;
revoke all on table public.match_sport_participant_events from public, anon, authenticated;
revoke all on sequence public.match_sport_participant_events_id_seq from public, anon, authenticated;
revoke all on table private.sport_admin_audit_log from public, anon, authenticated;
revoke all on sequence private.sport_admin_audit_log_id_seq from public, anon, authenticated;
grant select on table public.match_sport_workflows to authenticated;
grant select on table public.match_sport_participants to authenticated;
grant select on table public.match_sport_participant_events to authenticated;
grant select, insert, update on table public.match_sport_workflows to service_role;
grant select, insert, update on table public.match_sport_participants to service_role;
grant select, insert on table public.match_sport_participant_events to service_role;
grant usage, select on sequence public.match_sport_participant_events_id_seq to service_role;
grant select, insert on table private.sport_admin_audit_log to service_role;
grant usage, select on sequence private.sport_admin_audit_log_id_seq to service_role;
create or replace function private.require_sports_management_enabled()
returns void
language plpgsql
stable
security definer
set search_path = ''
as $function$
begin
  if not private.is_feature_enabled('sports_management') then
    raise exception 'Sports-management module is disabled' using errcode = '42501';
  end if;
end;
$function$;
create or replace function private.can_read_sport_workflow(p_match_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select private.is_feature_enabled('sports_management')
    and private.is_active_profile()
    and (
      private.is_admin()
      or exists (
        select 1
        from public.match_sport_participants participant
        join public.season_players player on player.id = participant.season_player_id
        where participant.match_id = p_match_id
          and player.profile_id = (select auth.uid())
      )
    );
$function$;
create or replace function private.can_read_sport_participant(p_participant_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select private.is_feature_enabled('sports_management')
    and private.is_active_profile()
    and (
      private.is_admin()
      or exists (
        select 1
        from public.match_sport_participants participant
        join public.season_players player on player.id = participant.season_player_id
        where participant.id = p_participant_id
          and player.profile_id = (select auth.uid())
      )
    );
$function$;
create policy match_sport_workflows_authorized_select
on public.match_sport_workflows for select to authenticated
using ((select private.can_read_sport_workflow(match_id)));
create policy match_sport_participants_authorized_select
on public.match_sport_participants for select to authenticated
using ((select private.can_read_sport_participant(id)));
create policy match_sport_participant_events_authorized_select
on public.match_sport_participant_events for select to authenticated
using ((select private.can_read_sport_participant(participant_id)));
;
