-- Optional sports-management module: workflows, permanent participants and availability.
-- Additive and inert while private.app_feature_flags.sports_management is false.

create type public.sport_availability_state as enum ('pending', 'open', 'closed');
create type public.sport_composition_state as enum ('none', 'draft', 'published', 'updated', 'closed');
create type public.sport_presence_state as enum ('pending', 'confirmed');
create type public.sport_vote_state as enum ('unavailable', 'draft', 'open', 'closed', 'cancelled');
create type public.sport_availability_status as enum ('no_response', 'available', 'absent', 'not_applicable');
create type public.sport_selection_status as enum ('undecided', 'starter', 'substitute', 'not_selected');
create type public.sport_final_presence_status as enum ('pending', 'present', 'actual_absent');

create table public.match_sport_workflows (
  match_id uuid primary key references public.matches(id) on delete restrict,
  availability_state public.sport_availability_state not null default 'pending',
  availability_opens_at timestamptz not null,
  availability_opened_at timestamptz,
  composition_state public.sport_composition_state not null default 'none',
  composition_version integer not null default 0 check (composition_version >= 0),
  squad_size_limit smallint not null default 14 check (squad_size_limit between 1 and 30),
  presence_state public.sport_presence_state not null default 'pending',
  vote_state public.sport_vote_state not null default 'unavailable',
  created_by uuid not null references public.profiles(id) on delete restrict,
  updated_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.match_sport_workflows is
  'Per-match state machine for the optional sports-management module.';
comment on column public.match_sport_workflows.availability_opens_at is
  'Absolute opening instant derived from matches.kickoff_at and server configuration.';
comment on column public.match_sport_workflows.squad_size_limit is
  'Default 14; later staff workflows may override it per match with audit.';

create table public.match_sport_participants (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.match_sport_workflows(match_id) on delete restrict,
  season_player_id uuid not null references public.season_players(id) on delete restrict,
  is_eligible boolean not null default true,
  availability_status public.sport_availability_status not null default 'no_response',
  availability_comment_private text,
  availability_updated_at timestamptz,
  availability_updated_by uuid references public.profiles(id) on delete set null,
  selection_status public.sport_selection_status not null default 'undecided',
  selection_updated_at timestamptz,
  selection_updated_by uuid references public.profiles(id) on delete set null,
  final_presence_status public.sport_final_presence_status not null default 'pending',
  final_presence_confirmed_at timestamptz,
  final_presence_confirmed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, season_player_id),
  unique (id, match_id),
  check (
    availability_comment_private is null
    or char_length(availability_comment_private) <= 500
  ),
  check (
    availability_comment_private is null
    or availability_status = 'absent'
  )
);

comment on table public.match_sport_participants is
  'Permanent roster participants. Guest identities are introduced by a later isolated migration.';
comment on column public.match_sport_participants.availability_comment_private is
  'Private absence comment visible only to its player and active administrators.';
comment on column public.match_sport_participants.final_presence_status is
  'Actual attendance, intentionally independent from availability and selection.';

create table public.match_sport_participant_events (
  id bigint generated by default as identity primary key,
  participant_id uuid not null,
  match_id uuid not null,
  event_type text not null check (
    event_type ~ '^[a-z][a-z0-9_]*$' and char_length(event_type) <= 64
  ),
  old_value jsonb check (old_value is null or jsonb_typeof(old_value) = 'object'),
  new_value jsonb check (new_value is null or jsonb_typeof(new_value) = 'object'),
  actor_profile_id uuid references public.profiles(id) on delete set null,
  actor_kind text not null check (actor_kind in ('player', 'staff', 'system')),
  created_at timestamptz not null default now(),
  foreign key (participant_id, match_id)
    references public.match_sport_participants(id, match_id) on delete restrict
);

comment on table public.match_sport_participant_events is
  'Append-only history for availability responses and later staff decisions.';

create table private.sport_admin_audit_log (
  id bigint generated by default as identity primary key,
  match_id uuid references public.matches(id) on delete set null,
  action text not null check (
    action ~ '^[a-z][a-z0-9_]*$' and char_length(action) <= 96
  ),
  actor_profile_id uuid not null references public.profiles(id) on delete restrict,
  reason text check (reason is null or char_length(reason) <= 500),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

comment on table private.sport_admin_audit_log is
  'Private append-only audit trail for privileged sports-management actions.';

create index match_sport_workflows_availability_due_idx
  on public.match_sport_workflows (availability_state, availability_opens_at);
create index match_sport_participants_match_status_idx
  on public.match_sport_participants (match_id, availability_status)
  where is_eligible;
create index match_sport_participants_season_player_idx
  on public.match_sport_participants (season_player_id);
create index match_sport_participant_events_timeline_idx
  on public.match_sport_participant_events (participant_id, created_at desc);
create index if not exists season_players_profile_id_idx
  on public.season_players (profile_id)
  where profile_id is not null;
create index sport_admin_audit_log_match_timeline_idx
  on private.sport_admin_audit_log (match_id, created_at desc);

alter table public.match_sport_workflows enable row level security;
alter table public.match_sport_participants enable row level security;
alter table public.match_sport_participant_events enable row level security;
alter table private.sport_admin_audit_log enable row level security;

revoke all on table public.match_sport_workflows from public, anon, authenticated;
revoke all on table public.match_sport_participants from public, anon, authenticated;
revoke all on table public.match_sport_participant_events from public, anon, authenticated;
revoke all on sequence public.match_sport_participant_events_id_seq from public, anon, authenticated;
revoke all on table private.sport_admin_audit_log from public, anon, authenticated;
revoke all on sequence private.sport_admin_audit_log_id_seq from public, anon, authenticated;

grant select on table public.match_sport_workflows to authenticated;
grant select on table public.match_sport_participants to authenticated;
grant select on table public.match_sport_participant_events to authenticated;
grant select, insert, update on table public.match_sport_workflows to service_role;
grant select, insert, update on table public.match_sport_participants to service_role;
grant select, insert on table public.match_sport_participant_events to service_role;
grant usage, select on sequence public.match_sport_participant_events_id_seq to service_role;
grant select, insert on table private.sport_admin_audit_log to service_role;
grant usage, select on sequence private.sport_admin_audit_log_id_seq to service_role;

create or replace function private.require_sports_management_enabled()
returns void
language plpgsql
stable
security definer
set search_path = ''
as $function$
begin
  if not private.is_feature_enabled('sports_management') then
    raise exception 'Sports-management module is disabled' using errcode = '42501';
  end if;
end;
$function$;

create or replace function private.can_read_sport_workflow(p_match_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select private.is_feature_enabled('sports_management')
    and private.is_active_profile()
    and (
      private.is_admin()
      or exists (
        select 1
        from public.match_sport_participants participant
        join public.season_players player on player.id = participant.season_player_id
        where participant.match_id = p_match_id
          and player.profile_id = (select auth.uid())
      )
    );
$function$;

create or replace function private.can_read_sport_participant(p_participant_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select private.is_feature_enabled('sports_management')
    and private.is_active_profile()
    and (
      private.is_admin()
      or exists (
        select 1
        from public.match_sport_participants participant
        join public.season_players player on player.id = participant.season_player_id
        where participant.id = p_participant_id
          and player.profile_id = (select auth.uid())
      )
    );
$function$;

create policy match_sport_workflows_authorized_select
on public.match_sport_workflows for select to authenticated
using ((select private.can_read_sport_workflow(match_id)));

create policy match_sport_participants_authorized_select
on public.match_sport_participants for select to authenticated
using ((select private.can_read_sport_participant(id)));

create policy match_sport_participant_events_authorized_select
on public.match_sport_participant_events for select to authenticated
using ((select private.can_read_sport_participant(participant_id)));

create or replace function private.sync_match_sport_workflow(p_match_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor uuid := (select auth.uid());
  v_season_id uuid;
  v_kickoff_at timestamptz;
  v_match_status text;
  v_config jsonb;
  v_open_hours integer := 144;
  v_default_squad_size integer := 14;
  v_opens_at timestamptz;
  v_computed_state public.sport_availability_state;
  v_saved_state public.sport_availability_state;
  v_opened_at timestamptz;
  v_eligible_count integer;
begin
  perform private.require_sports_management_enabled();
  if not private.is_admin() then
    raise exception 'Active administrator role required' using errcode = '42501';
  end if;

  select m.season_id, m.kickoff_at, m.status
  into v_season_id, v_kickoff_at, v_match_status
  from public.matches m
  where m.id = p_match_id
  for update;

  if not found then
    raise exception 'Match not found' using errcode = 'P0002';
  end if;
  if v_match_status <> 'a_venir' then
    raise exception 'Only upcoming matches can be synchronized' using errcode = '22023';
  end if;
  if v_kickoff_at is null then
    raise exception 'Match kickoff is required' using errcode = '22023';
  end if;

  select f.config into v_config
  from private.app_feature_flags f
  where f.key = 'sports_management';

  if coalesce(v_config ->> 'availability_open_hours_before', '') ~ '^[0-9]+$' then
    v_open_hours := greatest(
      1,
      least(720, (v_config ->> 'availability_open_hours_before')::integer)
    );
  end if;
  if coalesce(v_config ->> 'usual_squad_size', '') ~ '^[0-9]+$' then
    v_default_squad_size := greatest(
      1,
      least(30, (v_config ->> 'usual_squad_size')::integer)
    );
  end if;

  v_opens_at := v_kickoff_at - make_interval(hours => v_open_hours);
  v_computed_state := case
    when now() >= v_kickoff_at then 'closed'::public.sport_availability_state
    when now() >= v_opens_at then 'open'::public.sport_availability_state
    else 'pending'::public.sport_availability_state
  end;

  insert into public.match_sport_workflows as workflow (
    match_id, availability_state, availability_opens_at,
    availability_opened_at, squad_size_limit, created_by, updated_by
  ) values (
    p_match_id, v_computed_state, v_opens_at,
    case when v_computed_state = 'open' then now() else null end,
    v_default_squad_size, v_actor, v_actor
  )
  on conflict (match_id) do update
  set availability_opens_at = excluded.availability_opens_at,
      availability_state = case
        when now() >= v_kickoff_at then 'closed'::public.sport_availability_state
        when workflow.availability_state = 'open' then 'open'::public.sport_availability_state
        when now() >= v_opens_at then 'open'::public.sport_availability_state
        else 'pending'::public.sport_availability_state
      end,
      availability_opened_at = case
        when workflow.availability_opened_at is not null then workflow.availability_opened_at
        when now() >= v_opens_at and now() < v_kickoff_at then now()
        else null
      end,
      updated_by = v_actor,
      updated_at = now()
  returning availability_state, availability_opened_at
  into v_saved_state, v_opened_at;

  update public.match_sport_participants participant
  set is_eligible = false, updated_at = now()
  where participant.match_id = p_match_id
    and participant.is_eligible
    and not exists (
      select 1
      from public.season_players player
      join public.profiles profile on profile.id = player.profile_id
      where player.id = participant.season_player_id
        and player.season_id = v_season_id
        and player.is_active
        and profile.status = 'active'
    );

  insert into public.match_sport_participants as participant (
    match_id, season_player_id, is_eligible
  )
  select p_match_id, player.id, true
  from public.season_players player
  join public.profiles profile on profile.id = player.profile_id
  where player.season_id = v_season_id
    and player.is_active
    and profile.status = 'active'
  on conflict (match_id, season_player_id) do update
  set is_eligible = true,
      updated_at = case when participant.is_eligible then participant.updated_at else now() end;

  select count(*)::integer into v_eligible_count
  from public.match_sport_participants participant
  where participant.match_id = p_match_id and participant.is_eligible;

  return jsonb_build_object(
    'match_id', p_match_id,
    'availability_state', v_saved_state,
    'availability_opens_at', v_opens_at,
    'availability_opened_at', v_opened_at,
    'kickoff_at', v_kickoff_at,
    'squad_size_limit', (
      select workflow.squad_size_limit
      from public.match_sport_workflows workflow
      where workflow.match_id = p_match_id
    ),
    'eligible_participant_count', v_eligible_count
  );
end;
$function$;

create or replace function private.set_my_match_availability(
  p_match_id uuid,
  p_status text,
  p_private_comment text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor uuid := (select auth.uid());
  v_participant_id uuid;
  v_old_status public.sport_availability_status;
  v_old_comment text;
  v_new_status public.sport_availability_status;
  v_new_comment text := nullif(btrim(p_private_comment), '');
  v_workflow_state public.sport_availability_state;
  v_opens_at timestamptz;
  v_kickoff_at timestamptz;
  v_composition_state public.sport_composition_state;
  v_changed boolean;
begin
  perform private.require_sports_management_enabled();
  if not private.is_active_profile() then
    raise exception 'Active profile required' using errcode = '42501';
  end if;
  if p_status is null or p_status not in ('available', 'absent') then
    raise exception 'Availability status must be available or absent' using errcode = '22023';
  end if;

  v_new_status := p_status::public.sport_availability_status;
  if v_new_status = 'available' then v_new_comment := null; end if;
  if v_new_comment is not null and char_length(v_new_comment) > 500 then
    raise exception 'Availability comment cannot exceed 500 characters' using errcode = '22023';
  end if;

  select participant.id, participant.availability_status,
    participant.availability_comment_private, workflow.availability_state,
    workflow.availability_opens_at, workflow.composition_state, match.kickoff_at
  into v_participant_id, v_old_status, v_old_comment, v_workflow_state,
    v_opens_at, v_composition_state, v_kickoff_at
  from public.match_sport_participants participant
  join public.season_players player on player.id = participant.season_player_id
  join public.match_sport_workflows workflow on workflow.match_id = participant.match_id
  join public.matches match on match.id = participant.match_id
  where participant.match_id = p_match_id
    and participant.is_eligible
    and player.profile_id = v_actor
  for update of participant, workflow;

  if not found then
    raise exception 'Eligible match participant not found' using errcode = 'P0002';
  end if;
  if now() < v_opens_at then
    raise exception 'Availability window is not open yet' using errcode = '22023';
  end if;
  if now() >= v_kickoff_at then
    raise exception 'Availability window is closed' using errcode = '22023';
  end if;

  if v_workflow_state = 'pending' then
    update public.match_sport_workflows workflow
    set availability_state = 'open',
        availability_opened_at = coalesce(workflow.availability_opened_at, now()),
        updated_by = v_actor,
        updated_at = now()
    where workflow.match_id = p_match_id;
    v_workflow_state := 'open';
  end if;
  if v_workflow_state <> 'open' then
    raise exception 'Availability window is closed' using errcode = '22023';
  end if;

  v_changed := v_old_status is distinct from v_new_status
    or v_old_comment is distinct from v_new_comment;

  if v_changed then
    update public.match_sport_participants participant
    set availability_status = v_new_status,
        availability_comment_private = v_new_comment,
        availability_updated_at = now(),
        availability_updated_by = v_actor,
        updated_at = now()
    where participant.id = v_participant_id;

    insert into public.match_sport_participant_events (
      participant_id, match_id, event_type, old_value, new_value,
      actor_profile_id, actor_kind
    ) values (
      v_participant_id, p_match_id, 'availability_changed',
      jsonb_build_object('status', v_old_status, 'private_comment', v_old_comment),
      jsonb_build_object('status', v_new_status, 'private_comment', v_new_comment),
      v_actor, 'player'
    );
  end if;

  return jsonb_build_object(
    'match_id', p_match_id,
    'participant_id', v_participant_id,
    'availability_status', v_new_status,
    'private_comment', v_new_comment,
    'changed', v_changed,
    'composition_already_published',
      v_composition_state in ('published', 'updated', 'closed')
  );
end;
$function$;

create or replace function private.override_match_availability(
  p_match_id uuid,
  p_season_player_id uuid,
  p_status text,
  p_private_comment text default null,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor uuid := (select auth.uid());
  v_participant_id uuid;
  v_old_status public.sport_availability_status;
  v_old_comment text;
  v_new_status public.sport_availability_status;
  v_new_comment text := nullif(btrim(p_private_comment), '');
  v_reason text := nullif(btrim(p_reason), '');
  v_workflow_state public.sport_availability_state;
  v_opens_at timestamptz;
  v_kickoff_at timestamptz;
  v_changed boolean;
begin
  perform private.require_sports_management_enabled();
  if not private.is_admin() then
    raise exception 'Active administrator role required' using errcode = '42501';
  end if;
  if p_status is null or p_status not in ('no_response', 'available', 'absent') then
    raise exception 'Invalid availability override status' using errcode = '22023';
  end if;
  if v_reason is null then
    raise exception 'Override reason is required' using errcode = '22023';
  end if;
  if char_length(v_reason) > 500 then
    raise exception 'Override reason cannot exceed 500 characters' using errcode = '22023';
  end if;

  v_new_status := p_status::public.sport_availability_status;
  if v_new_status <> 'absent' then v_new_comment := null; end if;
  if v_new_comment is not null and char_length(v_new_comment) > 500 then
    raise exception 'Availability comment cannot exceed 500 characters' using errcode = '22023';
  end if;

  select participant.id, participant.availability_status,
    participant.availability_comment_private, workflow.availability_state,
    workflow.availability_opens_at, match.kickoff_at
  into v_participant_id, v_old_status, v_old_comment, v_workflow_state,
    v_opens_at, v_kickoff_at
  from public.match_sport_participants participant
  join public.match_sport_workflows workflow on workflow.match_id = participant.match_id
  join public.matches match on match.id = participant.match_id
  where participant.match_id = p_match_id
    and participant.season_player_id = p_season_player_id
    and participant.is_eligible
  for update of participant, workflow;

  if not found then
    raise exception 'Eligible match participant not found' using errcode = 'P0002';
  end if;
  if now() < v_opens_at then
    raise exception 'Availability window is not open yet' using errcode = '22023';
  end if;
  if now() >= v_kickoff_at then
    raise exception 'Availability window is closed' using errcode = '22023';
  end if;

  if v_workflow_state = 'pending' then
    update public.match_sport_workflows workflow
    set availability_state = 'open',
        availability_opened_at = coalesce(workflow.availability_opened_at, now()),
        updated_by = v_actor,
        updated_at = now()
    where workflow.match_id = p_match_id;
  elsif v_workflow_state <> 'open' then
    raise exception 'Availability window is closed' using errcode = '22023';
  end if;

  v_changed := v_old_status is distinct from v_new_status
    or v_old_comment is distinct from v_new_comment;

  if v_changed then
    update public.match_sport_participants participant
    set availability_status = v_new_status,
        availability_comment_private = v_new_comment,
        availability_updated_at = now(),
        availability_updated_by = v_actor,
        updated_at = now()
    where participant.id = v_participant_id;

    insert into public.match_sport_participant_events (
      participant_id, match_id, event_type, old_value, new_value,
      actor_profile_id, actor_kind
    ) values (
      v_participant_id, p_match_id, 'availability_changed',
      jsonb_build_object('status', v_old_status, 'private_comment', v_old_comment),
      jsonb_build_object('status', v_new_status, 'private_comment', v_new_comment),
      v_actor, 'staff'
    );

    insert into private.sport_admin_audit_log (
      match_id, action, actor_profile_id, reason, metadata
    ) values (
      p_match_id, 'override_availability', v_actor, v_reason,
      jsonb_build_object(
        'participant_id', v_participant_id,
        'season_player_id', p_season_player_id,
        'old_status', v_old_status,
        'new_status', v_new_status
      )
    );
  end if;

  return jsonb_build_object(
    'match_id', p_match_id,
    'participant_id', v_participant_id,
    'availability_status', v_new_status,
    'private_comment', v_new_comment,
    'changed', v_changed
  );
end;
$function$;

create or replace function private.get_my_match_availability(p_match_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_actor uuid := (select auth.uid());
  v_result jsonb;
begin
  perform private.require_sports_management_enabled();
  if not private.is_active_profile() then
    raise exception 'Active profile required' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'match_id', participant.match_id,
    'participant_id', participant.id,
    'season_player_id', participant.season_player_id,
    'is_eligible', participant.is_eligible,
    'availability_status', participant.availability_status,
    'private_comment', participant.availability_comment_private,
    'availability_updated_at', participant.availability_updated_at,
    'availability_state', case
      when now() >= match.kickoff_at then 'closed'
      when now() >= workflow.availability_opens_at
        and workflow.availability_state = 'pending' then 'open'
      else workflow.availability_state::text
    end,
    'availability_opens_at', workflow.availability_opens_at,
    'kickoff_at', match.kickoff_at,
    'can_respond', participant.is_eligible
      and now() >= workflow.availability_opens_at
      and now() < match.kickoff_at
      and workflow.availability_state <> 'closed',
    'composition_state', workflow.composition_state
  ) into v_result
  from public.match_sport_participants participant
  join public.season_players player on player.id = participant.season_player_id
  join public.match_sport_workflows workflow on workflow.match_id = participant.match_id
  join public.matches match on match.id = participant.match_id
  where participant.match_id = p_match_id and player.profile_id = v_actor;

  if v_result is null then
    raise exception 'Match participant not found' using errcode = 'P0002';
  end if;
  return v_result;
end;
$function$;

create or replace function public.admin_sync_match_sport_workflow(p_match_id uuid)
returns jsonb language sql volatile security invoker set search_path = ''
as $function$ select private.sync_match_sport_workflow(p_match_id); $function$;

create or replace function public.set_my_match_availability(
  p_match_id uuid, p_status text, p_private_comment text default null
)
returns jsonb language sql volatile security invoker set search_path = ''
as $function$
  select private.set_my_match_availability(p_match_id, p_status, p_private_comment);
$function$;

create or replace function public.admin_override_match_availability(
  p_match_id uuid,
  p_season_player_id uuid,
  p_status text,
  p_private_comment text default null,
  p_reason text default null
)
returns jsonb language sql volatile security invoker set search_path = ''
as $function$
  select private.override_match_availability(
    p_match_id, p_season_player_id, p_status, p_private_comment, p_reason
  );
$function$;

create or replace function public.get_my_match_availability(p_match_id uuid)
returns jsonb language sql stable security invoker set search_path = ''
as $function$ select private.get_my_match_availability(p_match_id); $function$;

revoke execute on function private.require_sports_management_enabled() from public, anon;
revoke execute on function private.can_read_sport_workflow(uuid) from public, anon;
revoke execute on function private.can_read_sport_participant(uuid) from public, anon;
revoke execute on function private.sync_match_sport_workflow(uuid) from public, anon;
revoke execute on function private.set_my_match_availability(uuid, text, text) from public, anon;
revoke execute on function private.override_match_availability(uuid, uuid, text, text, text) from public, anon;
revoke execute on function private.get_my_match_availability(uuid) from public, anon;

grant execute on function private.require_sports_management_enabled() to authenticated, service_role;
grant execute on function private.can_read_sport_workflow(uuid) to authenticated, service_role;
grant execute on function private.can_read_sport_participant(uuid) to authenticated, service_role;
grant execute on function private.sync_match_sport_workflow(uuid) to authenticated, service_role;
grant execute on function private.set_my_match_availability(uuid, text, text) to authenticated, service_role;
grant execute on function private.override_match_availability(uuid, uuid, text, text, text) to authenticated, service_role;
grant execute on function private.get_my_match_availability(uuid) to authenticated, service_role;

revoke execute on function public.admin_sync_match_sport_workflow(uuid) from public, anon;
revoke execute on function public.set_my_match_availability(uuid, text, text) from public, anon;
revoke execute on function public.admin_override_match_availability(uuid, uuid, text, text, text) from public, anon;
revoke execute on function public.get_my_match_availability(uuid) from public, anon;

grant execute on function public.admin_sync_match_sport_workflow(uuid) to authenticated, service_role;
grant execute on function public.set_my_match_availability(uuid, text, text) to authenticated, service_role;
grant execute on function public.admin_override_match_availability(uuid, uuid, text, text, text) to authenticated, service_role;
grant execute on function public.get_my_match_availability(uuid) to authenticated, service_role;

comment on function public.admin_sync_match_sport_workflow(uuid) is
  'Admin-only idempotent synchronization of an upcoming match and eligible permanent participants.';
comment on function public.set_my_match_availability(uuid, text, text) is
  'Records the signed-in eligible player availability during the server-enforced window.';
comment on function public.admin_override_match_availability(uuid, uuid, text, text, text) is
  'Admin-only availability override with a mandatory audit reason.';
comment on function public.get_my_match_availability(uuid) is
  'Returns the signed-in player private availability state and effective response window.';
