-- Corrige le branchement des préférences push et ajoute un journal technique
-- par abonnement, sans stocker l’URL complète de l’endpoint.

create table if not exists public.push_delivery_log (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  kind text not null check (kind in ('new_match', 'closing_soon', 'result_validated')),
  profile_id uuid references public.profiles(id) on delete set null,
  endpoint_host text,
  success boolean not null,
  status_code integer,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists idx_push_delivery_log_created_at
  on public.push_delivery_log (created_at desc);
create index if not exists idx_push_delivery_log_profile
  on public.push_delivery_log (profile_id, created_at desc);
create index if not exists idx_push_delivery_log_match_kind
  on public.push_delivery_log (match_id, kind, created_at desc);

alter table public.push_delivery_log enable row level security;
revoke all on table public.push_delivery_log from public, anon, authenticated;
grant select, insert on table public.push_delivery_log to service_role;
grant usage, select on sequence public.push_delivery_log_id_seq to service_role;

create or replace function public.internal_push_dispatch(
  p_kind text,
  p_match_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_match record;
  v_payload jsonb;
  v_subs jsonb;
begin
  select m.id,
         m.score_as_grinta,
         m.score_adverse,
         o.name as opponent_name,
         ((m.match_date + coalesce(m.match_time, '00:00'::time))
           at time zone 'Europe/Paris') as kickoff
  into v_match
  from public.matches m
  join public.opponents o on o.id = m.opponent_id
  where m.id = p_match_id;

  if not found then
    raise exception 'Match introuvable';
  end if;

  if p_kind = 'new_match' then
    v_payload := jsonb_build_object(
      'title', 'Nouveau match à pronostiquer',
      'body', format(
        'AS Grinta – %s le %s. Les pronostics sont ouverts !',
        v_match.opponent_name,
        to_char(v_match.kickoff at time zone 'Europe/Paris', 'DD/MM à HH24hMI')
      ),
      'url', '.',
      'tag', 'match-' || v_match.id || '-new'
    );

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'profile_id', ps.profile_id,
          'endpoint', ps.endpoint,
          'p256dh', ps.p256dh,
          'auth', ps.auth
        )
      ),
      '[]'::jsonb
    )
    into v_subs
    from public.push_subscriptions ps
    join public.profiles pr on pr.id = ps.profile_id
    where pr.status = 'active'
      and pr.notify_prediction_open;

  elsif p_kind = 'closing_soon' then
    v_payload := jsonb_build_object(
      'title', 'Dernière chance de pronostiquer',
      'body', format(
        'AS Grinta – %s : les pronostics ferment à %s.',
        v_match.opponent_name,
        to_char(
          (v_match.kickoff - interval '5 minutes') at time zone 'Europe/Paris',
          'HH24hMI'
        )
      ),
      'url', '.',
      'tag', 'match-' || v_match.id || '-closing'
    );

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'profile_id', ps.profile_id,
          'endpoint', ps.endpoint,
          'p256dh', ps.p256dh,
          'auth', ps.auth
        )
      ),
      '[]'::jsonb
    )
    into v_subs
    from public.push_subscriptions ps
    join public.profiles pr on pr.id = ps.profile_id
    where pr.status = 'active'
      and pr.notify_prediction_reminders
      and not exists (
        select 1
        from public.match_predictions mp
        where mp.match_id = p_match_id
          and mp.profile_id = pr.id
          and mp.is_filled
      );

  elsif p_kind = 'result_validated' then
    v_payload := jsonb_build_object(
      'title', 'Résultat validé',
      'body', format(
        'AS Grinta %s-%s %s. Découvre tes points et le classement !',
        coalesce(v_match.score_as_grinta::text, '?'),
        coalesce(v_match.score_adverse::text, '?'),
        v_match.opponent_name
      ),
      'url', '.',
      'tag', 'match-' || v_match.id || '-result'
    );

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'profile_id', ps.profile_id,
          'endpoint', ps.endpoint,
          'p256dh', ps.p256dh,
          'auth', ps.auth
        )
      ),
      '[]'::jsonb
    )
    into v_subs
    from public.push_subscriptions ps
    join public.profiles pr on pr.id = ps.profile_id
    where pr.status = 'active'
      and pr.notify_match_reminders;

  else
    raise exception 'Type d''envoi inconnu: %', p_kind;
  end if;

  return jsonb_build_object(
    'payload', v_payload,
    'subscriptions', v_subs
  );
end;
$$;

revoke all on function public.internal_push_dispatch(text, uuid)
  from public, anon, authenticated;
grant execute on function public.internal_push_dispatch(text, uuid)
  to service_role;
