-- Optional sports-management module: server-side feature flag foundation.
--
-- This migration is intentionally inert at runtime: the flag is inserted as
-- disabled and no existing application workflow is changed.

create schema if not exists private;

create table if not exists private.app_feature_flags (
  key text primary key,
  enabled boolean not null default false,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid null references public.profiles(id) on delete set null,
  constraint app_feature_flags_key_format
    check (key ~ '^[a-z][a-z0-9_]*$'),
  constraint app_feature_flags_config_object
    check (jsonb_typeof(config) = 'object')
);

comment on table private.app_feature_flags is
  'Server-side feature flags. This schema is not exposed through the Data API.';
comment on column private.app_feature_flags.enabled is
  'Authoritative server value. Flutter caches this value for presentation only.';

create table if not exists private.app_feature_flag_audit (
  id bigint generated by default as identity primary key,
  feature_key text not null references private.app_feature_flags(key)
    on update cascade on delete restrict,
  old_enabled boolean not null,
  new_enabled boolean not null,
  actor_profile_id uuid null references public.profiles(id) on delete set null,
  justification text null,
  created_at timestamptz not null default now(),
  constraint app_feature_flag_audit_real_transition
    check (old_enabled is distinct from new_enabled),
  constraint app_feature_flag_audit_justification_length
    check (justification is null or char_length(justification) <= 500)
);

comment on table private.app_feature_flag_audit is
  'Append-only audit trail for feature-flag state transitions.';

alter table private.app_feature_flags enable row level security;
alter table private.app_feature_flag_audit enable row level security;

revoke all on table private.app_feature_flags
  from public, anon, authenticated;
revoke all on table private.app_feature_flag_audit
  from public, anon, authenticated;
revoke all on sequence private.app_feature_flag_audit_id_seq
  from public, anon, authenticated;

grant select, insert, update on table private.app_feature_flags to service_role;
grant select, insert on table private.app_feature_flag_audit to service_role;
grant usage, select on sequence private.app_feature_flag_audit_id_seq
  to service_role;

insert into private.app_feature_flags (
  key,
  enabled,
  config,
  updated_at,
  updated_by
)
values (
  'sports_management',
  false,
  jsonb_build_object(
    'availability_open_hours_before', 144,
    'reminder_hours_before', jsonb_build_array(72, 24),
    'usual_squad_size', 14,
    'vote_duration_hours', 24,
    'timezone', 'Europe/Paris'
  ),
  now(),
  null
)
on conflict (key) do nothing;

create or replace function private.is_feature_enabled(p_key text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select f.enabled
      from private.app_feature_flags f
      where f.key = p_key
    ),
    false
  );
$$;

create or replace function private.get_public_feature_flags()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'sports_management',
    jsonb_build_object(
      'enabled', f.enabled,
      'config', f.config,
      'updated_at', f.updated_at
    )
  )
  from private.app_feature_flags f
  where f.key = 'sports_management';
$$;

create or replace function private.set_sports_management_enabled(
  p_enabled boolean,
  p_justification text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_old_enabled boolean;
  v_config jsonb;
  v_updated_at timestamptz;
  v_justification text := nullif(btrim(p_justification), '');
begin
  if p_enabled is null then
    raise exception 'Feature flag value is required' using errcode = '22023';
  end if;

  if not private.is_admin() then
    raise exception 'Active administrator role required' using errcode = '42501';
  end if;

  if v_justification is not null and char_length(v_justification) > 500 then
    raise exception 'Justification cannot exceed 500 characters'
      using errcode = '22023';
  end if;

  select f.enabled, f.config
  into v_old_enabled, v_config
  from private.app_feature_flags f
  where f.key = 'sports_management'
  for update;

  if not found then
    raise exception 'Sports-management feature flag is missing'
      using errcode = 'P0002';
  end if;

  if v_old_enabled is distinct from p_enabled then
    update private.app_feature_flags f
    set enabled = p_enabled,
        updated_at = now(),
        updated_by = (select auth.uid())
    where f.key = 'sports_management'
    returning f.updated_at into v_updated_at;

    insert into private.app_feature_flag_audit (
      feature_key,
      old_enabled,
      new_enabled,
      actor_profile_id,
      justification
    )
    values (
      'sports_management',
      v_old_enabled,
      p_enabled,
      (select auth.uid()),
      v_justification
    );
  else
    select f.updated_at
    into v_updated_at
    from private.app_feature_flags f
    where f.key = 'sports_management';
  end if;

  return jsonb_build_object(
    'sports_management',
    jsonb_build_object(
      'enabled', p_enabled,
      'config', v_config,
      'updated_at', v_updated_at,
      'changed', v_old_enabled is distinct from p_enabled
    )
  );
end;
$function$;

-- Public RPC wrappers remain SECURITY INVOKER. Privileged access is isolated in
-- private-schema helpers, which are not exposed by the Supabase Data API.
create or replace function public.get_public_feature_flags()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select private.get_public_feature_flags();
$$;

create or replace function public.set_sports_management_enabled(
  p_enabled boolean,
  p_justification text default null
)
returns jsonb
language sql
volatile
security invoker
set search_path = ''
as $$
  select private.set_sports_management_enabled(p_enabled, p_justification);
$$;

revoke execute on function private.is_feature_enabled(text)
  from public, anon;
revoke execute on function private.get_public_feature_flags()
  from public, anon;
revoke execute on function private.set_sports_management_enabled(boolean, text)
  from public, anon;

grant execute on function private.is_feature_enabled(text)
  to authenticated, service_role;
grant execute on function private.get_public_feature_flags()
  to authenticated, service_role;
grant execute on function private.set_sports_management_enabled(boolean, text)
  to authenticated;

revoke execute on function public.get_public_feature_flags()
  from public, anon;
revoke execute on function public.set_sports_management_enabled(boolean, text)
  from public, anon;

grant execute on function public.get_public_feature_flags()
  to authenticated, service_role;
grant execute on function public.set_sports_management_enabled(boolean, text)
  to authenticated;

comment on function public.get_public_feature_flags() is
  'Returns public-safe server feature flags for authenticated application users.';
comment on function public.set_sports_management_enabled(boolean, text) is
  'Admin-only toggle for the optional sports-management module, with audit.';
