-- P0: rate-limit the unauthenticated registration Edge Function.
-- Only a SHA-256 digest of the network origin is stored.

create table if not exists private.registration_attempts (
  id bigint generated by default as identity primary key,
  origin_hash text not null,
  attempted_at timestamptz not null default now(),
  constraint registration_attempts_origin_hash_check
    check (origin_hash ~ '^[0-9a-f]{64}$')
);

create index if not exists registration_attempts_origin_time_idx
  on private.registration_attempts(origin_hash, attempted_at desc);

create index if not exists registration_attempts_time_idx
  on private.registration_attempts(attempted_at desc);

create or replace function public.consume_registration_rate_limit(
  p_origin_hash text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_origin_hour integer;
  v_origin_day integer;
  v_global_hour integer;
begin
  if p_origin_hash is null or p_origin_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid origin hash' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_origin_hash, 0)
  );

  delete from private.registration_attempts
  where attempted_at < now() - interval '24 hours';

  select count(*)::integer
  into v_origin_hour
  from private.registration_attempts
  where origin_hash = p_origin_hash
    and attempted_at >= now() - interval '1 hour';

  select count(*)::integer
  into v_origin_day
  from private.registration_attempts
  where origin_hash = p_origin_hash
    and attempted_at >= now() - interval '24 hours';

  select count(*)::integer
  into v_global_hour
  from private.registration_attempts
  where attempted_at >= now() - interval '1 hour';

  if v_origin_hour >= 5 or v_origin_day >= 15 or v_global_hour >= 30 then
    return false;
  end if;

  insert into private.registration_attempts(origin_hash)
  values (p_origin_hash);

  return true;
end;
$$;

revoke all on table private.registration_attempts from public, anon, authenticated;
revoke execute on function public.consume_registration_rate_limit(text)
  from public, anon, authenticated;
grant execute on function public.consume_registration_rate_limit(text)
  to service_role;
