-- Schéma minimal requis par la vue de bascule des statistiques joueurs et
-- l’export personnel. La production possède déjà ces colonnes.

alter table public.season_players
  add column if not exists is_coach boolean not null default false;

create table if not exists public.historical_player_statistics (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('previous', 'all_time')),
  season_name text,
  display_rank integer not null check (display_rank > 0),
  player_name text not null,
  is_goalkeeper boolean not null default false,
  matches_played integer not null default 0,
  wins integer not null default 0,
  draws integer not null default 0,
  losses integer not null default 0,
  goals integer not null default 0,
  hdm integer not null default 0,
  clean_sheets integer,
  source_label text not null default 'test',
  profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(scope, player_name)
);

alter table public.historical_player_statistics enable row level security;
revoke all on public.historical_player_statistics from anon;
grant select on public.historical_player_statistics to authenticated;
