-- Une personne réelle = une identité canonique durable.
-- Les comptes, effectifs, invités, statistiques et archives deviennent des
-- contextes qui pointent vers public.players au lieu d'être des identités.

create or replace function private.normalize_player_name(p_name text)
returns text
language sql
immutable
strict
set search_path to ''
as $function$
  select lower(regexp_replace(btrim(p_name), '\s+', ' ', 'g'));
$function$;

revoke all on function private.normalize_player_name(text) from public, anon, authenticated;

create table public.players (
  id uuid primary key default gen_random_uuid(),
  display_name text not null check (btrim(display_name) <> ''),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

comment on table public.players is
  'Identité canonique permanente d''une personne/joueur, indépendante du compte, de la saison et des matchs.';
comment on column public.players.display_name is
  'Libellé canonique. Les variantes historiques sont conservées dans player_aliases.';

alter table public.players enable row level security;
revoke all on table public.players from anon, authenticated;

create table public.player_aliases (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  alias text not null check (btrim(alias) <> ''),
  created_at timestamptz not null default now()
);

comment on table public.player_aliases is
  'Variantes de nom connues d''une identité canonique. Un même libellé peut rester ambigu entre plusieurs personnes.';

create unique index player_aliases_player_normalized_alias_uidx
  on public.player_aliases(player_id, private.normalize_player_name(alias));
create index player_aliases_normalized_alias_idx
  on public.player_aliases(private.normalize_player_name(alias));

alter table public.player_aliases enable row level security;
revoke all on table public.player_aliases from anon, authenticated;

alter table public.profiles
  add column if not exists player_id uuid references public.players(id) on delete restrict;
alter table public.season_players
  add column if not exists player_id uuid references public.players(id) on delete restrict;
alter table public.guest_players
  add column if not exists player_id uuid references public.players(id) on delete restrict;
alter table public.historical_player_statistics
  add column if not exists player_id uuid references public.players(id) on delete restrict;

create index if not exists profiles_player_id_idx
  on public.profiles(player_id) where player_id is not null;
create index if not exists season_players_player_id_idx
  on public.season_players(player_id);
create index if not exists guest_players_player_id_idx
  on public.guest_players(player_id);
create index if not exists historical_player_statistics_player_id_idx
  on public.historical_player_statistics(player_id);

-- Les profils réels déjà existants deviennent les premières racines. On
-- réutilise leur UUID pour obtenir un backfill déterministe, sans identifiants
-- générés codés en dur. Le compte technique d'import n'est pas une personne.
insert into public.players(id, display_name, created_at, updated_at)
select
  p.id,
  coalesce(
    nullif(btrim(concat_ws(' ', p.first_name, nullif(p.last_name, ''))), ''),
    nullif(btrim(p.username), ''),
    'Joueur'
  ),
  coalesce(p.created_at, now()),
  coalesce(p.updated_at, now())
from public.profiles p
where coalesce(p.email, '') <> 'historique@as-grinta.invalid'
on conflict (id) do nothing;

update public.profiles p
set player_id = p.id
where coalesce(p.email, '') <> 'historique@as-grinta.invalid'
  and p.player_id is null;

insert into public.player_aliases(player_id, alias)
select p.player_id, concat_ws(' ', p.first_name, nullif(p.last_name, ''))
from public.profiles p
where p.player_id is not null
  and btrim(concat_ws(' ', p.first_name, nullif(p.last_name, ''))) <> ''
on conflict do nothing;

-- Les relations déjà validées par identifiant ont priorité sur tout
-- rapprochement par nom.
update public.season_players sp
set player_id = p.player_id
from public.profiles p
where sp.profile_id = p.id
  and p.player_id is not null
  and sp.player_id is null;

update public.historical_player_statistics h
set player_id = p.player_id
from public.profiles p
where h.profile_id = p.id
  and p.player_id is not null
  and h.player_id is null;

insert into public.player_aliases(player_id, alias)
select sp.player_id, concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))
from public.season_players sp
where sp.player_id is not null
  and btrim(concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))) <> ''
on conflict do nothing;

insert into public.player_aliases(player_id, alias)
select h.player_id, h.player_name
from public.historical_player_statistics h
where h.player_id is not null
  and btrim(coalesce(h.player_name, '')) <> ''
on conflict do nothing;

-- Une correspondance textuelle n'est utilisée automatiquement que lorsque le
-- libellé ne désigne qu'une seule identité déjà établie.
with unique_alias as (
  select
    private.normalize_player_name(a.alias) as normalized_name,
    min(a.player_id::text)::uuid as player_id
  from public.player_aliases a
  group by private.normalize_player_name(a.alias)
  having count(distinct a.player_id) = 1
)
update public.season_players sp
set player_id = ua.player_id
from unique_alias ua
where sp.player_id is null
  and private.normalize_player_name(
    concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))
  ) = ua.normalized_name;

with unique_alias as (
  select
    private.normalize_player_name(a.alias) as normalized_name,
    min(a.player_id::text)::uuid as player_id
  from public.player_aliases a
  group by private.normalize_player_name(a.alias)
  having count(distinct a.player_id) = 1
)
update public.guest_players g
set player_id = ua.player_id
from unique_alias ua
where g.player_id is null
  and private.normalize_player_name(
    concat_ws(' ', g.first_name, nullif(g.last_name, ''))
  ) = ua.normalized_name;

with unique_alias as (
  select
    private.normalize_player_name(a.alias) as normalized_name,
    min(a.player_id::text)::uuid as player_id
  from public.player_aliases a
  group by private.normalize_player_name(a.alias)
  having count(distinct a.player_id) = 1
)
update public.historical_player_statistics h
set player_id = ua.player_id
from unique_alias ua
where h.player_id is null
  and private.normalize_player_name(h.player_name) = ua.normalized_name;

insert into public.player_aliases(player_id, alias)
select sp.player_id, concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))
from public.season_players sp
where sp.player_id is not null
  and btrim(concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))) <> ''
on conflict do nothing;

insert into public.player_aliases(player_id, alias)
select g.player_id, concat_ws(' ', g.first_name, nullif(g.last_name, ''))
from public.guest_players g
where g.player_id is not null
  and btrim(concat_ws(' ', g.first_name, nullif(g.last_name, ''))) <> ''
on conflict do nothing;

insert into public.player_aliases(player_id, alias)
select h.player_id, h.player_name
from public.historical_player_statistics h
where h.player_id is not null
  and btrim(coalesce(h.player_name, '')) <> ''
on conflict do nothing;

-- Toutes les identités qui restent sans relation certaine sont volontairement
-- séparées. Les libellés strictement identiques et non résolus forment une
-- seule nouvelle identité ; une collision avec plusieurs identités existantes
-- crée au contraire une identité distincte au lieu de choisir arbitrairement.
create temporary table _canonical_player_seed on commit drop as
with alias_count as (
  select
    private.normalize_player_name(a.alias) as normalized_name,
    count(distinct a.player_id) as identity_count
  from public.player_aliases a
  group by private.normalize_player_name(a.alias)
),
archive_names as (
  select distinct
    private.normalize_player_name(n.player_name) as normalized_name,
    btrim(n.player_name) as display_name
  from public.historical_match_details h
  cross join lateral (
    select e ->> 'name' as player_name
    from jsonb_array_elements(coalesce(h.field_players, '[]'::jsonb)) e
    union all
    select jsonb_array_elements_text(coalesce(h.bench_players, '[]'::jsonb))
    union all
    select jsonb_array_elements_text(coalesce(h.present_names, '[]'::jsonb))
    union all
    select e ->> 'name'
    from jsonb_array_elements(coalesce(h.scorers, '[]'::jsonb)) e
    union all
    select jsonb_array_elements_text(coalesce(h.motm_names, '[]'::jsonb))
  ) n
  where btrim(coalesce(n.player_name, '')) <> ''
    and private.normalize_player_name(n.player_name)
      <> private.normalize_player_name('Poste laissé vide')
),
candidate as (
  select
    private.normalize_player_name(
      concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))
    ) as normalized_name,
    btrim(concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))) as display_name,
    10 as priority
  from public.season_players sp
  where sp.player_id is null

  union all

  select
    private.normalize_player_name(
      concat_ws(' ', g.first_name, nullif(g.last_name, ''))
    ),
    btrim(concat_ws(' ', g.first_name, nullif(g.last_name, ''))),
    20
  from public.guest_players g
  where g.player_id is null

  union all

  select
    private.normalize_player_name(h.player_name),
    btrim(h.player_name),
    30
  from public.historical_player_statistics h
  where h.player_id is null

  union all

  select an.normalized_name, an.display_name, 40
  from archive_names an
  left join alias_count ac using (normalized_name)
  where coalesce(ac.identity_count, 0) <> 1
),
ranked as (
  select
    c.*,
    row_number() over (
      partition by c.normalized_name
      order by c.priority, c.display_name
    ) as rn
  from candidate c
  where c.normalized_name <> ''
)
select gen_random_uuid() as player_id, normalized_name, display_name
from ranked
where rn = 1;

insert into public.players(id, display_name)
select s.player_id, s.display_name
from _canonical_player_seed s;

update public.season_players sp
set player_id = s.player_id
from _canonical_player_seed s
where sp.player_id is null
  and private.normalize_player_name(
    concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))
  ) = s.normalized_name;

update public.guest_players g
set player_id = s.player_id
from _canonical_player_seed s
where g.player_id is null
  and private.normalize_player_name(
    concat_ws(' ', g.first_name, nullif(g.last_name, ''))
  ) = s.normalized_name;

update public.historical_player_statistics h
set player_id = s.player_id
from _canonical_player_seed s
where h.player_id is null
  and private.normalize_player_name(h.player_name) = s.normalized_name;

insert into public.player_aliases(player_id, alias)
select s.player_id, s.display_name
from _canonical_player_seed s
on conflict do nothing;

insert into public.player_aliases(player_id, alias)
select sp.player_id, concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))
from public.season_players sp
where sp.player_id is not null
  and btrim(concat_ws(' ', sp.first_name, nullif(sp.last_name, ''))) <> ''
on conflict do nothing;

insert into public.player_aliases(player_id, alias)
select g.player_id, concat_ws(' ', g.first_name, nullif(g.last_name, ''))
from public.guest_players g
where g.player_id is not null
  and btrim(concat_ws(' ', g.first_name, nullif(g.last_name, ''))) <> ''
on conflict do nothing;

insert into public.player_aliases(player_id, alias)
select h.player_id, h.player_name
from public.historical_player_statistics h
where h.player_id is not null
  and btrim(coalesce(h.player_name, '')) <> ''
on conflict do nothing;

-- Résolution directe des libellés d'archives. Le mapping temporaire mémorise
-- le choix prudent effectué ci-dessus, y compris lorsqu'un nom était ambigu.
create temporary table _archive_player_map on commit drop as
with archive_names as (
  select distinct
    private.normalize_player_name(n.player_name) as normalized_name,
    btrim(n.player_name) as display_name
  from public.historical_match_details h
  cross join lateral (
    select e ->> 'name' as player_name
    from jsonb_array_elements(coalesce(h.field_players, '[]'::jsonb)) e
    union all
    select jsonb_array_elements_text(coalesce(h.bench_players, '[]'::jsonb))
    union all
    select jsonb_array_elements_text(coalesce(h.present_names, '[]'::jsonb))
    union all
    select e ->> 'name'
    from jsonb_array_elements(coalesce(h.scorers, '[]'::jsonb)) e
    union all
    select jsonb_array_elements_text(coalesce(h.motm_names, '[]'::jsonb))
  ) n
  where btrim(coalesce(n.player_name, '')) <> ''
    and private.normalize_player_name(n.player_name)
      <> private.normalize_player_name('Poste laissé vide')
),
unique_alias as (
  select
    private.normalize_player_name(a.alias) as normalized_name,
    min(a.player_id::text)::uuid as player_id
  from public.player_aliases a
  group by private.normalize_player_name(a.alias)
  having count(distinct a.player_id) = 1
)
select
  an.normalized_name,
  an.display_name,
  coalesce(seed.player_id, ua.player_id) as player_id
from archive_names an
left join _canonical_player_seed seed using (normalized_name)
left join unique_alias ua using (normalized_name);

do $assertions$
begin
  if exists (
    select 1
    from public.profiles p
    where coalesce(p.email, '') <> 'historique@as-grinta.invalid'
      and p.player_id is null
  ) then
    raise exception 'Canonical identity backfill failed for profiles';
  end if;

  if exists (select 1 from public.season_players where player_id is null) then
    raise exception 'Canonical identity backfill failed for season_players';
  end if;

  if exists (select 1 from public.guest_players where player_id is null) then
    raise exception 'Canonical identity backfill failed for guest_players';
  end if;

  if exists (
    select 1 from public.historical_player_statistics where player_id is null
  ) then
    raise exception 'Canonical identity backfill failed for historical statistics';
  end if;

  if exists (select 1 from _archive_player_map where player_id is null) then
    raise exception 'Canonical identity backfill failed for archived match names';
  end if;

  if exists (
    select 1
    from public.season_players sp
    join public.profiles p on p.id = sp.profile_id
    where p.player_id is not null
      and sp.player_id is distinct from p.player_id
  ) then
    raise exception 'Season/profile canonical identities disagree';
  end if;

  if exists (
    select 1
    from public.historical_player_statistics h
    join public.profiles p on p.id = h.profile_id
    where p.player_id is not null
      and h.player_id is distinct from p.player_id
  ) then
    raise exception 'Historical/profile canonical identities disagree';
  end if;
end
$assertions$;

alter table public.season_players alter column player_id set not null;
alter table public.guest_players alter column player_id set not null;
alter table public.historical_player_statistics alter column player_id set not null;

create table public.historical_match_players (
  match_id uuid not null references public.historical_match_scores(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  source_name text not null,
  is_present boolean not null default false,
  is_starter boolean not null default false,
  is_bench boolean not null default false,
  is_motm boolean not null default false,
  goals integer not null default 0 check (goals >= 0),
  is_goalkeeper boolean,
  x_pct numeric,
  y_pct numeric,
  position_code text,
  position_label text,
  created_at timestamptz not null default now(),
  primary key (match_id, player_id)
);

comment on table public.historical_match_players is
  'Projection normalisée des joueurs des matchs importés, reliée à l''identité canonique. Les JSON historiques restent conservés pour compatibilité.';

create index historical_match_players_player_id_idx
  on public.historical_match_players(player_id);

alter table public.historical_match_players enable row level security;
revoke all on table public.historical_match_players from anon, authenticated;

with field_row as (
  select
    h.match_id,
    btrim(e ->> 'name') as source_name,
    private.normalize_player_name(e ->> 'name') as normalized_name,
    true as is_present,
    true as is_starter,
    false as is_bench,
    false as is_motm,
    0::integer as goals,
    (e ->> 'is_gk')::boolean as is_goalkeeper,
    (e ->> 'x_pct')::numeric as x_pct,
    (e ->> 'y_pct')::numeric as y_pct,
    e ->> 'position_code' as position_code,
    e ->> 'position_label' as position_label
  from public.historical_match_details h
  cross join lateral jsonb_array_elements(coalesce(h.field_players, '[]'::jsonb)) e
  where btrim(coalesce(e ->> 'name', '')) <> ''
    and private.normalize_player_name(e ->> 'name')
      <> private.normalize_player_name('Poste laissé vide')
),
bench_row as (
  select
    h.match_id,
    btrim(n.player_name) as source_name,
    private.normalize_player_name(n.player_name) as normalized_name,
    true, false, true, false, 0::integer,
    null::boolean, null::numeric, null::numeric, null::text, null::text
  from public.historical_match_details h
  cross join lateral jsonb_array_elements_text(coalesce(h.bench_players, '[]'::jsonb)) n(player_name)
  where btrim(coalesce(n.player_name, '')) <> ''
),
present_row as (
  select
    h.match_id,
    btrim(n.player_name) as source_name,
    private.normalize_player_name(n.player_name) as normalized_name,
    true, false, false, false, 0::integer,
    null::boolean, null::numeric, null::numeric, null::text, null::text
  from public.historical_match_details h
  cross join lateral jsonb_array_elements_text(coalesce(h.present_names, '[]'::jsonb)) n(player_name)
  where btrim(coalesce(n.player_name, '')) <> ''
),
scorer_row as (
  select
    h.match_id,
    btrim(e ->> 'name') as source_name,
    private.normalize_player_name(e ->> 'name') as normalized_name,
    true, false, false, false,
    coalesce((e ->> 'goals')::integer, 0),
    null::boolean, null::numeric, null::numeric, null::text, null::text
  from public.historical_match_details h
  cross join lateral jsonb_array_elements(coalesce(h.scorers, '[]'::jsonb)) e
  where btrim(coalesce(e ->> 'name', '')) <> ''
),
motm_row as (
  select
    h.match_id,
    btrim(n.player_name) as source_name,
    private.normalize_player_name(n.player_name) as normalized_name,
    true, false, false, true, 0::integer,
    null::boolean, null::numeric, null::numeric, null::text, null::text
  from public.historical_match_details h
  cross join lateral jsonb_array_elements_text(coalesce(h.motm_names, '[]'::jsonb)) n(player_name)
  where btrim(coalesce(n.player_name, '')) <> ''
),
all_row as (
  select * from field_row
  union all select * from bench_row
  union all select * from present_row
  union all select * from scorer_row
  union all select * from motm_row
),
aggregated as (
  select
    r.match_id,
    r.normalized_name,
    min(r.source_name) as source_name,
    bool_or(r.is_present) as is_present,
    bool_or(r.is_starter) as is_starter,
    bool_or(r.is_bench) as is_bench,
    bool_or(r.is_motm) as is_motm,
    sum(r.goals)::integer as goals,
    bool_or(r.is_goalkeeper) filter (where r.is_goalkeeper is not null) as is_goalkeeper,
    max(r.x_pct) as x_pct,
    max(r.y_pct) as y_pct,
    max(r.position_code) as position_code,
    max(r.position_label) as position_label
  from all_row r
  where r.normalized_name <> private.normalize_player_name('Poste laissé vide')
  group by r.match_id, r.normalized_name
)
insert into public.historical_match_players(
  match_id, player_id, source_name, is_present, is_starter, is_bench,
  is_motm, goals, is_goalkeeper, x_pct, y_pct, position_code, position_label
)
select
  a.match_id,
  m.player_id,
  a.source_name,
  a.is_present,
  a.is_starter,
  a.is_bench,
  a.is_motm,
  a.goals,
  a.is_goalkeeper,
  a.x_pct,
  a.y_pct,
  a.position_code,
  a.position_label
from aggregated a
join _archive_player_map m using (normalized_name)
on conflict (match_id, player_id) do update
set
  is_present = excluded.is_present or historical_match_players.is_present,
  is_starter = excluded.is_starter or historical_match_players.is_starter,
  is_bench = excluded.is_bench or historical_match_players.is_bench,
  is_motm = excluded.is_motm or historical_match_players.is_motm,
  goals = greatest(excluded.goals, historical_match_players.goals),
  is_goalkeeper = coalesce(excluded.is_goalkeeper, historical_match_players.is_goalkeeper),
  x_pct = coalesce(excluded.x_pct, historical_match_players.x_pct),
  y_pct = coalesce(excluded.y_pct, historical_match_players.y_pct),
  position_code = coalesce(excluded.position_code, historical_match_players.position_code),
  position_label = coalesce(excluded.position_label, historical_match_players.position_label);

-- Helpers privés pour garantir une identité aux nouvelles lignes sans réintroduire
-- de fusion automatique par nom lors de la création d'un joueur moderne.
create or replace function private.create_player_identity(p_display_name text)
returns uuid
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_player_id uuid;
  v_display_name text := nullif(btrim(p_display_name), '');
begin
  if v_display_name is null then
    raise exception 'Player display name is required' using errcode = '22023';
  end if;

  insert into public.players(display_name)
  values (v_display_name)
  returning id into v_player_id;

  insert into public.player_aliases(player_id, alias)
  values (v_player_id, v_display_name)
  on conflict do nothing;

  return v_player_id;
end;
$function$;

revoke all on function private.create_player_identity(text) from public, anon, authenticated;

create or replace function private.ensure_profile_player_identity()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if coalesce(new.email, '') = 'historique@as-grinta.invalid' then
    return new;
  end if;

  if new.player_id is null then
    new.player_id := private.create_player_identity(
      coalesce(
        nullif(btrim(concat_ws(' ', new.first_name, nullif(new.last_name, ''))), ''),
        nullif(btrim(new.username), ''),
        'Joueur'
      )
    );
  end if;

  return new;
end;
$function$;

create or replace function private.ensure_season_player_identity()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_player_id uuid;
begin
  if new.player_id is not null then
    return new;
  end if;

  if new.profile_id is not null then
    select p.player_id into v_profile_player_id
    from public.profiles p
    where p.id = new.profile_id;
  end if;

  new.player_id := coalesce(
    v_profile_player_id,
    private.create_player_identity(
      btrim(concat_ws(' ', new.first_name, nullif(new.last_name, '')))
    )
  );
  return new;
end;
$function$;

create or replace function private.ensure_guest_player_identity()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if new.player_id is null then
    new.player_id := private.create_player_identity(
      btrim(concat_ws(' ', new.first_name, nullif(new.last_name, '')))
    );
  end if;
  return new;
end;
$function$;

create or replace function private.ensure_historical_player_identity()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_player_id uuid;
  v_matched_player_id uuid;
begin
  if new.player_id is not null then
    return new;
  end if;

  if new.profile_id is not null then
    select p.player_id into v_profile_player_id
    from public.profiles p
    where p.id = new.profile_id;
  end if;

  if v_profile_player_id is not null then
    new.player_id := v_profile_player_id;
    return new;
  end if;

  select min(a.player_id::text)::uuid
  into v_matched_player_id
  from public.player_aliases a
  where private.normalize_player_name(a.alias)
    = private.normalize_player_name(new.player_name)
  having count(distinct a.player_id) = 1;

  new.player_id := coalesce(
    v_matched_player_id,
    private.create_player_identity(btrim(new.player_name))
  );
  return new;
end;
$function$;

revoke all on function private.ensure_profile_player_identity() from public, anon, authenticated;
revoke all on function private.ensure_season_player_identity() from public, anon, authenticated;
revoke all on function private.ensure_guest_player_identity() from public, anon, authenticated;
revoke all on function private.ensure_historical_player_identity() from public, anon, authenticated;

create trigger ensure_profile_player_identity_before_insert
before insert on public.profiles
for each row execute function private.ensure_profile_player_identity();

create trigger ensure_season_player_identity_before_insert
before insert on public.season_players
for each row execute function private.ensure_season_player_identity();

create trigger ensure_guest_player_identity_before_insert
before insert on public.guest_players
for each row execute function private.ensure_guest_player_identity();

create trigger ensure_historical_player_identity_before_insert
before insert on public.historical_player_statistics
for each row execute function private.ensure_historical_player_identity();

create or replace function private.capture_player_alias()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_alias text;
begin
  if new.player_id is null then
    return new;
  end if;

  case tg_table_name
    when 'profiles' then
      v_alias := btrim(concat_ws(' ', new.first_name, nullif(new.last_name, '')));
    when 'season_players' then
      v_alias := btrim(concat_ws(' ', new.first_name, nullif(new.last_name, '')));
    when 'guest_players' then
      v_alias := btrim(concat_ws(' ', new.first_name, nullif(new.last_name, '')));
    when 'historical_player_statistics' then
      v_alias := btrim(new.player_name);
    else
      return new;
  end case;

  if coalesce(v_alias, '') <> '' then
    insert into public.player_aliases(player_id, alias)
    values (new.player_id, v_alias)
    on conflict do nothing;
  end if;

  return new;
end;
$function$;

revoke all on function private.capture_player_alias() from public, anon, authenticated;

create trigger capture_profile_player_alias_after_write
after insert or update of first_name, last_name on public.profiles
for each row execute function private.capture_player_alias();

create trigger capture_season_player_alias_after_write
after insert or update of first_name, last_name on public.season_players
for each row execute function private.capture_player_alias();

create trigger capture_guest_player_alias_after_write
after insert or update of first_name, last_name on public.guest_players
for each row execute function private.capture_player_alias();

create trigger capture_historical_player_alias_after_write
after insert or update of player_name on public.historical_player_statistics
for each row execute function private.capture_player_alias();

-- Fusion interne utilisée seulement lorsqu'un lien explicite prouve qu'une
-- identité autonome et une identité de compte sont la même personne.
create or replace function private.merge_player_identities(
  p_source_player_id uuid,
  p_target_player_id uuid
)
returns void
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if p_source_player_id is null
     or p_target_player_id is null
     or p_source_player_id = p_target_player_id then
    return;
  end if;

  if not exists (
    select 1 from public.players p where p.id = p_source_player_id
  ) or not exists (
    select 1 from public.players p where p.id = p_target_player_id
  ) then
    raise exception 'Canonical player identity not found' using errcode = 'P0002';
  end if;

  -- Deux comptes déjà distincts constituent une ambiguïté réelle : aucune
  -- fusion automatique n'est autorisée.
  if exists (
    select 1 from public.profiles p where p.player_id = p_source_player_id
  ) then
    raise exception 'Cannot merge two account-backed player identities'
      using errcode = '23514';
  end if;

  -- Si les deux identités apparaissent séparément dans le même match archivé,
  -- on refuse de décider qu'il s'agit d'une seule personne.
  if exists (
    select 1
    from public.historical_match_players source_row
    join public.historical_match_players target_row
      on target_row.match_id = source_row.match_id
     and target_row.player_id = p_target_player_id
    where source_row.player_id = p_source_player_id
  ) then
    raise exception 'Archived match contains both player identities; manual resolution required'
      using errcode = '23514';
  end if;

  delete from public.player_aliases source_alias
  using public.player_aliases target_alias
  where source_alias.player_id = p_source_player_id
    and target_alias.player_id = p_target_player_id
    and private.normalize_player_name(source_alias.alias)
      = private.normalize_player_name(target_alias.alias);

  update public.player_aliases
  set player_id = p_target_player_id
  where player_id = p_source_player_id;

  update public.historical_match_players
  set player_id = p_target_player_id
  where player_id = p_source_player_id;

  update public.historical_player_statistics
  set player_id = p_target_player_id
  where player_id = p_source_player_id;

  update public.guest_players
  set player_id = p_target_player_id
  where player_id = p_source_player_id;

  update public.season_players
  set player_id = p_target_player_id
  where player_id = p_source_player_id;

  delete from public.players
  where id = p_source_player_id;
end;
$function$;

revoke all on function private.merge_player_identities(uuid, uuid)
  from public, anon, authenticated;

-- Les deux outils d'administration existants deviennent les points de fusion
-- explicites vers l'identité canonique.
create or replace function public.staff_set_season_player_profile(
  p_season_player_id uuid,
  p_profile_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_season_id uuid;
  v_source_player_id uuid;
  v_target_player_id uuid;
  v_profile_status text;
begin
  if not public.is_match_staff() then
    raise exception 'Active administrator role required' using errcode = '42501';
  end if;

  if p_season_player_id is null then
    raise exception 'Season player id is required' using errcode = '22023';
  end if;

  select sp.season_id, sp.player_id
  into v_season_id, v_source_player_id
  from public.season_players sp
  where sp.id = p_season_player_id
  for update;

  if not found then
    raise exception 'Season player not found' using errcode = 'P0002';
  end if;

  if p_profile_id is null then
    update public.season_players
    set profile_id = null
    where id = p_season_player_id;
    return true;
  end if;

  select p.status, p.player_id
  into v_profile_status, v_target_player_id
  from public.profiles p
  where p.id = p_profile_id
    and coalesce(p.email, '') <> 'historique@as-grinta.invalid'
  for update;

  if not found then
    raise exception 'Profile not found or protected technical account'
      using errcode = 'P0002';
  end if;

  if v_profile_status <> 'active' then
    raise exception 'Only an active profile can be linked' using errcode = '23514';
  end if;

  if v_target_player_id is null then
    raise exception 'Profile has no canonical player identity' using errcode = '23514';
  end if;

  update public.season_players
  set profile_id = null
  where season_id = v_season_id
    and profile_id = p_profile_id
    and id <> p_season_player_id;

  perform private.merge_player_identities(
    v_source_player_id,
    v_target_player_id
  );

  update public.season_players
  set profile_id = p_profile_id,
      player_id = v_target_player_id
  where id = p_season_player_id;

  return true;
end;
$function$;

revoke all on function public.staff_set_season_player_profile(uuid, uuid)
  from public, anon;
grant execute on function public.staff_set_season_player_profile(uuid, uuid)
  to authenticated;

create or replace function public.staff_set_historical_profile(
  p_profile_id uuid,
  p_historical_id bigint
)
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_name text;
  v_source_player_id uuid;
  v_target_player_id uuid;
begin
  if not public.is_match_staff() then
    raise exception 'Active administrator role required' using errcode = '42501';
  end if;

  if p_profile_id is null then
    raise exception 'Profile id is required' using errcode = '22023';
  end if;

  select p.player_id
  into v_target_player_id
  from public.profiles p
  where p.id = p_profile_id
    and coalesce(p.email, '') <> 'historique@as-grinta.invalid'
  for update;

  if not found or v_target_player_id is null then
    raise exception 'Profile not found or protected technical account'
      using errcode = 'P0002';
  end if;

  -- Détacher un ancien lien de compte ne détruit jamais l'identité réelle.
  update public.historical_player_statistics
  set profile_id = null, updated_at = now()
  where profile_id = p_profile_id;

  if p_historical_id is not null then
    select h.player_name, h.player_id
    into v_name, v_source_player_id
    from public.historical_player_statistics h
    where h.id = p_historical_id
    for update;

    if not found then
      raise exception 'Historical record not found' using errcode = 'P0002';
    end if;

    perform private.merge_player_identities(
      v_source_player_id,
      v_target_player_id
    );

    update public.historical_player_statistics h
    set profile_id = p_profile_id,
        player_id = v_target_player_id,
        updated_at = now()
    where h.player_id = v_target_player_id
      and private.normalize_player_name(h.player_name)
        = private.normalize_player_name(v_name);
  end if;

  perform public.recalculate_profile_badges(p_profile_id);
  return true;
end;
$function$;

revoke all on function public.staff_set_historical_profile(uuid, bigint)
  from public, anon;
grant execute on function public.staff_set_historical_profile(uuid, bigint)
  to authenticated;
