-- Optional sports-management module: availability opening and reminder notifications.
-- Additive and inert while private.app_feature_flags.sports_management is false.

alter table public.push_delivery_log
  drop constraint if exists push_delivery_log_kind_check;
alter table public.push_delivery_log
  add constraint push_delivery_log_kind_check check (
    kind in (
      'new_match',
      'closing_soon',
      'result_validated',
      'availability_open',
      'availability_j3',
      'availability_j1',
      'availability_manual'
    )
  );
create table public.sport_availability_notification_events (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.match_sport_workflows(match_id) on delete restrict,
  participant_id uuid not null,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  kind text not null check (
    kind in (
      'availability_open',
      'availability_j3',
      'availability_j1',
      'availability_manual'
    )
  ),
  source text not null check (source in ('automatic', 'manual')),
  scheduled_for timestamptz not null,
  requested_at timestamptz not null default now(),
  requested_by uuid references public.profiles(id) on delete set null,
  reason text check (reason is null or char_length(reason) <= 500),
  dispatch_status text not null default 'pending' check (
    dispatch_status in (
      'pending',
      'dispatch_requested',
      'completed',
      'no_subscription',
      'dispatch_failed'
    )
  ),
  dispatch_requested_at timestamptz,
  delivery_completed_at timestamptz,
  network_request_id bigint,
  attempted_count integer not null default 0 check (attempted_count >= 0),
  sent_count integer not null default 0 check (sent_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  created_at timestamptz not null default now(),
  foreign key (participant_id, match_id)
    references public.match_sport_participants(id, match_id) on delete restrict,
  check (
    (source = 'manual' and kind = 'availability_manual')
    or (source = 'automatic' and kind <> 'availability_manual')
  )
);
comment on table public.sport_availability_notification_events is
  'Per-player history and outbox for availability opening and reminder pushes.';
create unique index sport_availability_notification_auto_once_idx
  on public.sport_availability_notification_events(participant_id, kind)
  where source = 'automatic';
create index sport_availability_notification_match_timeline_idx
  on public.sport_availability_notification_events(match_id, requested_at desc);
create index sport_availability_notification_profile_timeline_idx
  on public.sport_availability_notification_events(profile_id, requested_at desc);
alter table public.sport_availability_notification_events enable row level security;
create or replace function public.internal_sport_push_dispatch(
  p_kind text,
  p_match_id uuid,
  p_profile_ids uuid[]
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_match record;
  v_payload jsonb;
  v_subscriptions jsonb;
begin
  if p_kind not in (
    'availability_open',
    'availability_j3',
    'availability_j1',
    'availability_manual'
  ) then
    raise exception 'Unknown sports notification kind' using errcode = '22023';
  end if;

  if p_profile_ids is null or cardinality(p_profile_ids) = 0 then
    return jsonb_build_object(
      'payload', '{}'::jsonb,
      'subscriptions', '[]'::jsonb
    );
  end if;

  select
    m.id,
    m.kickoff_at,
    o.name as opponent_name
  into v_match
  from public.matches m
  join public.opponents o on o.id = m.opponent_id
  where m.id = p_match_id;

  if not found then
    raise exception 'Match not found' using errcode = 'P0002';
  end if;

  v_payload := case p_kind
    when 'availability_open' then jsonb_build_object(
      'title', 'Disponibilités ouvertes',
      'body', format(
        'AS Grinta – %s le %s. Indique si tu es disponible ou absent.',
        v_match.opponent_name,
        to_char(v_match.kickoff_at at time zone 'Europe/Paris', 'DD/MM à HH24hMI')
      ),
      'url', '.',
      'tag', 'sport-' || p_match_id || '-availability-open'
    )
    when 'availability_j3' then jsonb_build_object(
      'title', 'Réponds pour le prochain match',
      'body', format(
        'AS Grinta – %s : tu n’as pas encore indiqué ta disponibilité.',
        v_match.opponent_name
      ),
      'url', '.',
      'tag', 'sport-' || p_match_id || '-availability-j3'
    )
    when 'availability_j1' then jsonb_build_object(
      'title', 'Dernier rappel disponibilité',
      'body', format(
        'AS Grinta – %s joue demain. Disponible ou absent ?',
        v_match.opponent_name
      ),
      'url', '.',
      'tag', 'sport-' || p_match_id || '-availability-j1'
    )
    else jsonb_build_object(
      'title', 'Le staff attend ta réponse',
      'body', format(
        'AS Grinta – %s : indique maintenant si tu es disponible ou absent.',
        v_match.opponent_name
      ),
      'url', '.',
      'tag', 'sport-' || p_match_id || '-availability-manual'
    )
  end;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'profile_id', subscription.profile_id,
        'endpoint', subscription.endpoint,
        'p256dh', subscription.p256dh,
        'auth', subscription.auth
      )
    ),
    '[]'::jsonb
  )
  into v_subscriptions
  from public.push_subscriptions subscription
  join public.profiles profile on profile.id = subscription.profile_id
  where subscription.profile_id = any(p_profile_ids)
    and profile.status = 'active'
    and profile.notify_match_reminders
    and exists (
      select 1
      from public.match_sport_participants participant
      join public.season_players player on player.id = participant.season_player_id
      where participant.match_id = p_match_id
        and participant.is_eligible
        and player.profile_id = subscription.profile_id
        and (
          p_kind = 'availability_open'
          or participant.availability_status = 'no_response'
        )
    );

  return jsonb_build_object(
    'payload', v_payload,
    'subscriptions', v_subscriptions
  );
end;
$function$;
create or replace function public.internal_mark_sport_notification_delivery(
  p_event_id bigint,
  p_attempted integer,
  p_sent integer,
  p_failed integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
begin
  update public.sport_availability_notification_events
  set attempted_count = greatest(coalesce(p_attempted, 0), 0),
      sent_count = greatest(coalesce(p_sent, 0), 0),
      failed_count = greatest(coalesce(p_failed, 0), 0),
      dispatch_status = case
        when greatest(coalesce(p_attempted, 0), 0) = 0 then 'no_subscription'
        else 'completed'
      end,
      delivery_completed_at = now()
  where id = p_event_id;

  return found;
end;
$function$;
create or replace function private.dispatch_sport_notification_event(p_event_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_event record;
  v_token text;
  v_request_id bigint;
begin
  select event.id, event.kind, event.match_id, event.profile_id
  into v_event
  from public.sport_availability_notification_events event
  where event.id = p_event_id
  for update;

  if not found then
    return false;
  end if;

  if v_event.id is null then
    return false;
  end if;

  select secret.decrypted_secret
  into v_token
  from vault.decrypted_secrets secret
  where secret.name = 'push_internal_token';

  if v_token is null then
    update public.sport_availability_notification_events
    set dispatch_status = 'dispatch_failed'
    where id = p_event_id;
    return false;
  end if;

  select net.http_post(
    url := 'https://ovzijmqrnsgcmryinkfa.supabase.co/functions/v1/send-push',
    body := jsonb_build_object(
      'kind', v_event.kind,
      'match_id', v_event.match_id,
      'profile_ids', jsonb_build_array(v_event.profile_id),
      'notification_event_id', v_event.id
    ),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-push-token', v_token
    ),
    timeout_milliseconds := 10000
  ) into v_request_id;

  update public.sport_availability_notification_events
  set dispatch_status = 'dispatch_requested',
      dispatch_requested_at = now(),
      network_request_id = v_request_id
  where id = p_event_id;

  return true;
exception
  when others then
    update public.sport_availability_notification_events
    set dispatch_status = 'dispatch_failed'
    where id = p_event_id;
    return false;
end;
$function$;
create or replace function private.create_sport_availability_notification(
  p_match_id uuid,
  p_participant_id uuid,
  p_profile_id uuid,
  p_kind text,
  p_source text,
  p_scheduled_for timestamptz,
  p_requested_by uuid,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_event_id bigint;
begin
  insert into public.sport_availability_notification_events (
    match_id,
    participant_id,
    profile_id,
    kind,
    source,
    scheduled_for,
    requested_by,
    reason
  ) values (
    p_match_id,
    p_participant_id,
    p_profile_id,
    p_kind,
    p_source,
    p_scheduled_for,
    p_requested_by,
    nullif(trim(p_reason), '')
  )
  on conflict do nothing
  returning id into v_event_id;

  if v_event_id is not null then
    perform private.dispatch_sport_notification_event(v_event_id);
  end if;

  return v_event_id;
end;
$function$;
;
