-- Module Statistiques : données historiques importées du fichier validé
-- et vue unifiée avec la saison ouverte.

create table if not exists public.historical_player_statistics (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('previous', 'all_time')),
  season_name text,
  display_rank integer not null check (display_rank > 0),
  player_name text not null check (nullif(btrim(player_name), '') is not null),
  is_goalkeeper boolean not null default false,
  matches_played integer not null check (matches_played >= 0),
  wins integer not null check (wins >= 0),
  draws integer not null check (draws >= 0),
  losses integer not null check (losses >= 0),
  goals integer not null default 0 check (goals >= 0),
  hdm integer not null default 0 check (hdm >= 0),
  clean_sheets integer check (clean_sheets is null or clean_sheets >= 0),
  source_label text not null default 'classements_joueurs_et_gardien_corriges',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (scope, player_name),
  check (
    (scope = 'previous' and season_name is not null)
    or (scope = 'all_time' and season_name is null)
  )
);

alter table public.historical_player_statistics enable row level security;

drop policy if exists "Authenticated users can read historical statistics"
  on public.historical_player_statistics;
create policy "Authenticated users can read historical statistics"
  on public.historical_player_statistics
  for select
  to authenticated
  using (true);

revoke all privileges on table public.historical_player_statistics from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.historical_player_statistics from authenticated;
grant select on table public.historical_player_statistics to authenticated;
grant usage, select on sequence public.historical_player_statistics_id_seq
  to service_role;

insert into public.historical_player_statistics (
  scope, season_name, display_rank, player_name, is_goalkeeper,
  matches_played, wins, draws, losses, goals, hdm, clean_sheets
)
values
  ('all_time', null, 1, 'Flo Arnauduc', false, 271, 179, 41, 47, 112, 8, null),
  ('all_time', null, 2, 'Olivier Millet', false, 250, 162, 41, 45, 6, 8, null),
  ('all_time', null, 3, 'Stéphane Fernandez', false, 248, 167, 37, 40, 17, 10, null),
  ('all_time', null, 4, 'Samuel Granier', false, 230, 151, 32, 44, 18, 6, null),
  ('all_time', null, 5, 'Romain Spigolon', false, 219, 143, 36, 37, 14, 9, null),
  ('all_time', null, 6, 'Milan Couzin', false, 155, 107, 16, 30, 201, 39, null),
  ('all_time', null, 7, 'François De La Bourdonnaye', false, 146, 94, 19, 32, 57, 5, null),
  ('all_time', null, 8, 'Luka Brunel', false, 122, 84, 14, 23, 35, 21, null),
  ('all_time', null, 9, 'Julio Vignard', false, 116, 77, 16, 21, 18, 3, null),
  ('all_time', null, 10, 'Julien Cesar', false, 106, 76, 12, 17, 25, 10, null),
  ('all_time', null, 11, 'Hakim Cherfi', false, 62, 44, 8, 9, 15, 8, null),
  ('all_time', null, 12, 'Simon Reis', false, 58, 38, 10, 10, 13, 3, null),
  ('all_time', null, 13, 'Alyoun Cherfi', false, 47, 35, 6, 5, 3, 4, null),
  ('all_time', null, 14, 'Aki Salabee', false, 32, 24, 4, 3, 4, 0, null),
  ('all_time', null, 15, 'Alban Ricard', false, 28, 18, 2, 7, 15, 5, null),
  ('all_time', null, 16, 'Allan Bamokena', false, 28, 20, 1, 7, 23, 2, null),
  ('all_time', null, 17, 'Amine Salhi', false, 20, 16, 2, 2, 7, 2, null),
  ('all_time', null, 18, 'Nicolas Belmonte', false, 20, 15, 1, 4, 28, 4, null),
  ('previous', '2025-2026', 1, 'Milan Couzin', false, 29, 19, 2, 7, 30, 5, null),
  ('previous', '2025-2026', 2, 'Allan Bamokena', false, 28, 20, 1, 7, 23, 2, null),
  ('previous', '2025-2026', 3, 'Flo Arnauduc', false, 28, 19, 2, 6, 6, 0, null),
  ('previous', '2025-2026', 4, 'Stéphane Fernandez', false, 28, 19, 2, 6, 1, 0, null),
  ('previous', '2025-2026', 5, 'Alban Ricard', false, 27, 17, 2, 7, 15, 5, null),
  ('previous', '2025-2026', 6, 'Luka Brunel', false, 27, 19, 2, 6, 11, 6, null),
  ('previous', '2025-2026', 7, 'Samuel Granier', false, 25, 16, 2, 6, 1, 1, null),
  ('previous', '2025-2026', 8, 'Romain Spigolon', false, 21, 13, 1, 6, 1, 0, null),
  ('previous', '2025-2026', 9, 'Alyoun Cherfi', false, 20, 14, 1, 4, 0, 1, null),
  ('previous', '2025-2026', 10, 'Nicolas Belmonte', false, 20, 15, 1, 4, 28, 4, null),
  ('previous', '2025-2026', 11, 'Julio Vignard', false, 19, 12, 2, 5, 1, 0, null),
  ('previous', '2025-2026', 12, 'Amine Salhi', false, 17, 13, 2, 2, 7, 2, null),
  ('previous', '2025-2026', 13, 'Julien Cesar', false, 15, 8, 1, 5, 3, 0, null),
  ('previous', '2025-2026', 14, 'Aki Salabee', false, 14, 10, 1, 2, 3, 0, null),
  ('previous', '2025-2026', 15, 'Olivier Millet', false, 14, 7, 1, 5, 0, 1, null),
  ('previous', '2025-2026', 16, 'François De La Bourdonnaye', false, 9, 6, 0, 3, 1, 0, null),
  ('previous', '2025-2026', 17, 'Hakim Cherfi', false, 9, 8, 0, 1, 2, 1, null),
  ('previous', '2025-2026', 18, 'Simon Reis', false, 4, 3, 0, 1, 0, 0, null),
  ('all_time', null, 1, 'Samih Châa', true, 134, 90, 16, 26, 0, 16, 21),
  ('previous', '2025-2026', 1, 'Samih Châa', true, 21, 15, 2, 3, 0, 4, 3)
on conflict (scope, player_name) do update set
  season_name = excluded.season_name,
  display_rank = excluded.display_rank,
  is_goalkeeper = excluded.is_goalkeeper,
  matches_played = excluded.matches_played,
  wins = excluded.wins,
  draws = excluded.draws,
  losses = excluded.losses,
  goals = excluded.goals,
  hdm = excluded.hdm,
  clean_sheets = excluded.clean_sheets,
  updated_at = now();

create or replace view public.v_statistics_players
with (security_invoker = true)
as
with current_season as (
  select id, name
  from public.seasons
  where status = 'open'
  order by created_at desc
  limit 1
),
current_base as (
  select
    cs.name as period_label,
    sp.position as display_order,
    sp.first_name as player_name,
    sp.is_goalkeeper,
    coalesce(st.goals, 0)::integer as goals,
    coalesce(st.clean_sheets, 0)::integer as clean_sheets,
    case
      when sp.is_goalkeeper then coalesce(st.clean_sheets, 0)
      else coalesce(st.goals, 0)
    end::integer as ranking_metric
  from current_season cs
  join public.season_players sp
    on sp.season_id = cs.id
   and sp.is_active
  left join public.v_player_season_stats st
    on st.season_player_id = sp.id
),
current_ranked as (
  select
    'current'::text as period_key,
    period_label,
    rank() over (
      partition by is_goalkeeper
      order by ranking_metric desc
    )::integer as display_rank,
    coalesce(display_order, 9999)::integer as display_order,
    player_name,
    is_goalkeeper,
    null::integer as matches_played,
    null::integer as wins,
    null::integer as draws,
    null::integer as losses,
    goals,
    null::integer as hdm,
    clean_sheets
  from current_base
),
historical as (
  select
    scope as period_key,
    case
      when scope = 'previous' then season_name
      else 'Toutes saisons terminées'
    end as period_label,
    display_rank,
    display_rank as display_order,
    player_name,
    is_goalkeeper,
    matches_played,
    wins,
    draws,
    losses,
    goals,
    hdm,
    clean_sheets
  from public.historical_player_statistics
)
select * from current_ranked
union all
select * from historical;

revoke all privileges on table public.v_statistics_players from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.v_statistics_players from authenticated;
grant select on table public.v_statistics_players to authenticated;