-- Durcit le test de notifications push :
-- - seuls les profils actifs peuvent appeler la RPC ;
-- - au plus 3 envois réellement remis au pipeline par fenêtre de 10 minutes ;
-- - le quota est sérialisé par profil pour éviter les contournements concurrents.

create table if not exists private.test_push_attempts (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  attempted_at timestamptz not null default now()
);

alter table private.test_push_attempts enable row level security;

revoke all on table private.test_push_attempts from public, anon, authenticated;

create index if not exists test_push_attempts_profile_created_idx
  on private.test_push_attempts (profile_id, attempted_at desc);

comment on table private.test_push_attempts is
  'Server-side rate-limit ledger for self test push notifications.';

create or replace function public.send_test_push()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_token text;
  v_actor uuid := (select auth.uid());
  v_subscriptions integer;
  v_recent_attempts integer;
begin
  if v_actor is null or not private.is_active_profile() then
    raise exception 'Active profile required' using errcode = '42501';
  end if;

  -- Un seul appel par profil évalue/consomme le quota à la fois.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('send_test_push:' || v_actor::text, 0)
  );

  delete from private.test_push_attempts attempt
  where attempt.profile_id = v_actor
    and attempt.attempted_at < now() - interval '1 day';

  select count(*)::integer
  into v_recent_attempts
  from private.test_push_attempts attempt
  where attempt.profile_id = v_actor
    and attempt.attempted_at >= now() - interval '10 minutes';

  if v_recent_attempts >= 3 then
    return jsonb_build_object(
      'sent', false,
      'reason', 'rate_limited'
    );
  end if;

  select count(*)
  into v_subscriptions
  from public.push_subscriptions subscription
  where subscription.profile_id = v_actor;

  if v_subscriptions = 0 then
    return jsonb_build_object(
      'sent', false,
      'reason', 'no_subscription'
    );
  end if;

  if coalesce(
       (private.get_notifications_paused()
          #>> '{notifications_paused,enabled}')::boolean,
       false
     ) then
    return jsonb_build_object(
      'sent', false,
      'reason', 'notifications_paused'
    );
  end if;

  select decrypted_secret into v_token
  from vault.decrypted_secrets
  where name = 'push_internal_token';

  if v_token is null then
    return jsonb_build_object(
      'sent', false,
      'reason', 'not_configured'
    );
  end if;

  insert into private.test_push_attempts (profile_id)
  values (v_actor);

  perform net.http_post(
    url := 'https://ovzijmqrnsgcmryinkfa.supabase.co/functions/v1/send-push',
    body := jsonb_build_object(
      'kind', 'test',
      'profile_ids', jsonb_build_array(v_actor)
    ),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-push-token', v_token
    ),
    timeout_milliseconds := 10000
  );

  return jsonb_build_object(
    'sent', true,
    'subscriptions', v_subscriptions
  );
end;
$$;

revoke all on function public.send_test_push() from public, anon;
grant execute on function public.send_test_push() to authenticated;

comment on function public.send_test_push() is
  'Sends a self-only test push for active profiles, capped at 3 sends per 10 minutes.';
