begin;

-- Reconstitue la composition des 15 matchs d'archives joués avec Samih qui
-- n'en avaient pas (seule la liste des présents était connue).
--
-- Ces compositions sont des reconstitutions, pas des feuilles d'époque :
-- formation reprise des matchs voisins, joueurs placés à leur poste habituel
-- sur la même période. Quand l'effectif était incomplet, les postes restants
-- sont marqués « Poste laissé vide », comme dans les autres archives.
-- Philippe Couzin, présent sur les feuilles mais jamais aligné ni remplaçant
-- dans aucune archive, n'est pas placé.
--
-- Garde-fous : seule une archive encore sans composition est modifiée, et
-- chaque personne présente (hors Philippe Couzin) doit être placée une fois,
-- sans aucun nom absent de la feuille. Une base sans ces archives (schéma
-- isolé de test) ne fait rien.

do $$
declare
  v_row record;
  v_present jsonb;
  v_expected text[];
  v_placed text[];
begin
  for v_row in
    select * from (values
    ('e995e302-8958-4309-b6a2-30b0d74f1ed6'::uuid, date '2022-01-05', '4-2-3-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Stéphane Manenti", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 33, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 67, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Julio Vignard", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 24.8, "y_pct": 49, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 75.2, "y_pct": 49, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Arnold Hajdini", "is_gk": false, "x_pct": 10.9, "y_pct": 21.7, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 50, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Kevin Jagot", "is_gk": false, "x_pct": 89.1, "y_pct": 21.7, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '[]'::jsonb, '["Samih Châa", "Stéphane Manenti", "Olivier Millet", "Samuel Granier", "Julio Vignard", "Flo Arnauduc", "Arnold Hajdini", "Kevin Jagot", "Milan Couzin"]'::jsonb),
    ('a56f018b-a746-4942-bbae-5a0d62a0656b'::uuid, date '2022-01-13', '4-2-3-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Stéphane Manenti", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 33, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Julio Vignard", "is_gk": false, "x_pct": 67, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Thomas Blanchard", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Roman Yassinski", "is_gk": false, "x_pct": 24.8, "y_pct": 49, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 75.2, "y_pct": 49, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 10.9, "y_pct": 21.7, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 50, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Arnold Hajdini", "is_gk": false, "x_pct": 89.1, "y_pct": 21.7, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '[]'::jsonb, '["Samih Châa", "Stéphane Manenti", "Olivier Millet", "Julio Vignard", "Thomas Blanchard", "Roman Yassinski", "Flo Arnauduc", "Arnold Hajdini", "Milan Couzin"]'::jsonb),
    ('e506c5c2-672c-47b7-be45-29ddabf673e1'::uuid, date '2022-05-19', '4-4-1-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Stéphane Manenti", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 31.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 68.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Dorian Larrieu", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Thomas Blanchard", "is_gk": false, "x_pct": 10, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Romain Spigolon", "is_gk": false, "x_pct": 31.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 68.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Kevin Jagot", "is_gk": false, "x_pct": 90, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 50, "y_pct": 26.2, "position_code": "ATT", "position_label": "Attaquant"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Arnold Hajdini", "Samuel Granier", "Roman Yassinski"]'::jsonb, '["Samih Châa", "Stéphane Manenti", "Stéphane Fernandez", "Olivier Millet", "Dorian Larrieu", "Thomas Blanchard", "Romain Spigolon", "Luka Brunel", "Kevin Jagot", "Flo Arnauduc", "Milan Couzin", "Arnold Hajdini", "Samuel Granier", "Roman Yassinski"]'::jsonb),
    ('65c8de83-9170-44cc-b4a2-c0bd202a84ba'::uuid, date '2022-06-23', '4-2-3-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Stéphane Manenti", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 33, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 67, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Julio Vignard", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Romain Spigolon", "is_gk": false, "x_pct": 24.8, "y_pct": 49, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Roman Yassinski", "is_gk": false, "x_pct": 75.2, "y_pct": 49, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Thomas Blanchard", "is_gk": false, "x_pct": 10.9, "y_pct": 21.7, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 50, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Kevin Jagot", "is_gk": false, "x_pct": 89.1, "y_pct": 21.7, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Arnold Hajdini", "Luka Brunel", "Simon Reis"]'::jsonb, '["Samih Châa", "Stéphane Manenti", "Stéphane Fernandez", "Olivier Millet", "Julio Vignard", "Romain Spigolon", "Roman Yassinski", "Thomas Blanchard", "Flo Arnauduc", "Kevin Jagot", "Milan Couzin", "Arnold Hajdini", "Luka Brunel", "Simon Reis"]'::jsonb),
    ('6e770f4e-7209-40bc-8c7f-d89deff3beae'::uuid, date '2022-09-21', '4-4-1-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Stéphane Manenti", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Julien Cesar", "is_gk": false, "x_pct": 31.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 68.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 10, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Romain Spigolon", "is_gk": false, "x_pct": 31.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 68.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Kevin Jagot", "is_gk": false, "x_pct": 90, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 26.2, "position_code": "ATT", "position_label": "Attaquant"}, {"name": "Yoann Canal", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Arnold Hajdini", "Thomas Blanchard", "Dorian Larrieu", "Simon Reis", "Julio Vignard", "Hakim Cherfi"]'::jsonb, '["Samih Châa", "Stéphane Manenti", "Julien Cesar", "Olivier Millet", "Samuel Granier", "Flo Arnauduc", "Romain Spigolon", "Luka Brunel", "Kevin Jagot", "Milan Couzin", "Yoann Canal", "Arnold Hajdini", "Thomas Blanchard", "Dorian Larrieu", "Simon Reis", "Julio Vignard", "Hakim Cherfi"]'::jsonb),
    ('10a8552c-d386-4993-b629-c2c88d581e98'::uuid, date '2023-06-22', '4-4-1-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Stéphane Manenti", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 31.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 68.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "François De La Bourdonnaye", "is_gk": false, "x_pct": 10, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 31.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 68.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Hakim Cherfi", "is_gk": false, "x_pct": 90, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 26.2, "position_code": "ATT", "position_label": "Attaquant"}, {"name": "Yoann Canal", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Thomas Blanchard", "Romain Spigolon", "Roman Yassinski"]'::jsonb, '["Samih Châa", "Stéphane Manenti", "Olivier Millet", "Stéphane Fernandez", "Samuel Granier", "François De La Bourdonnaye", "Flo Arnauduc", "Luka Brunel", "Hakim Cherfi", "Milan Couzin", "Yoann Canal", "Thomas Blanchard", "Romain Spigolon", "Roman Yassinski"]'::jsonb),
    ('916c8e7a-a8dd-43a7-85e9-9c23eebc1274'::uuid, date '2023-06-28', '4-4-1-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Stéphane Manenti", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 31.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 68.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "François De La Bourdonnaye", "is_gk": false, "x_pct": 10, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 31.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 68.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Hakim Cherfi", "is_gk": false, "x_pct": 90, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Arnold Hajdini", "is_gk": false, "x_pct": 50, "y_pct": 26.2, "position_code": "ATT", "position_label": "Attaquant"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Julien Cesar", "Thomas Blanchard", "Simon Reis"]'::jsonb, '["Samih Châa", "Stéphane Manenti", "Olivier Millet", "Stéphane Fernandez", "Samuel Granier", "François De La Bourdonnaye", "Flo Arnauduc", "Luka Brunel", "Hakim Cherfi", "Arnold Hajdini", "Milan Couzin", "Julien Cesar", "Thomas Blanchard", "Simon Reis"]'::jsonb),
    ('b95d8190-312e-4504-97e0-6250897d906e'::uuid, date '2023-12-21', '4-1-4-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Julien Cesar", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Simon Reis", "is_gk": false, "x_pct": 30, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 70, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Dorian Larrieu", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Roman Yassinski", "is_gk": false, "x_pct": 50, "y_pct": 52.1, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "François De La Bourdonnaye", "is_gk": false, "x_pct": 10, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 33, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 67, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Kevin Jagot", "is_gk": false, "x_pct": 90, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Arnold Hajdini", "Yoann Canal", "Hakim Cherfi"]'::jsonb, '["Samih Châa", "Julien Cesar", "Simon Reis", "Stéphane Fernandez", "Dorian Larrieu", "Roman Yassinski", "François De La Bourdonnaye", "Flo Arnauduc", "Luka Brunel", "Kevin Jagot", "Milan Couzin", "Arnold Hajdini", "Yoann Canal", "Hakim Cherfi"]'::jsonb),
    ('7831a89b-47ee-431a-b4d9-9f9db0086698'::uuid, date '2024-02-15', '4-4-1-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Thomas Blanchard", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 31.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 68.5, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Julio Vignard", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 10, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 31.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Roman Yassinski", "is_gk": false, "x_pct": 68.5, "y_pct": 46.9, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 90, "y_pct": 36.5, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Yoann Canal", "is_gk": false, "x_pct": 50, "y_pct": 26.2, "position_code": "ATT", "position_label": "Attaquant"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '[]'::jsonb, '["Samih Châa", "Thomas Blanchard", "Stéphane Fernandez", "Julio Vignard", "Flo Arnauduc", "Roman Yassinski", "Yoann Canal", "Milan Couzin"]'::jsonb),
    ('c70163c6-0f0e-4ed7-810e-c59261a11170'::uuid, date '2024-06-12', '4-1-4-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Thomas Blanchard", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Aki Salabee", "is_gk": false, "x_pct": 30, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 70, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Arnold Hajdini", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Romain Spigolon", "is_gk": false, "x_pct": 50, "y_pct": 52.1, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "François De La Bourdonnaye", "is_gk": false, "x_pct": 10, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 33, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 67, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Kevin Jagot", "is_gk": false, "x_pct": 90, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Roman Yassinski"]'::jsonb, '["Samih Châa", "Thomas Blanchard", "Aki Salabee", "Stéphane Fernandez", "Arnold Hajdini", "Romain Spigolon", "François De La Bourdonnaye", "Flo Arnauduc", "Luka Brunel", "Kevin Jagot", "Milan Couzin", "Roman Yassinski"]'::jsonb),
    ('10c4c4aa-e4d7-4843-8e52-6fab8e493752'::uuid, date '2025-02-20', '4-1-4-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Alyoun Cherfi", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Aki Salabee", "is_gk": false, "x_pct": 30, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 70, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Simon Reis", "is_gk": false, "x_pct": 50, "y_pct": 52.1, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "François De La Bourdonnaye", "is_gk": false, "x_pct": 10, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 33, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 67, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Hakim Cherfi", "is_gk": false, "x_pct": 90, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Yoann Canal"]'::jsonb, '["Samih Châa", "Alyoun Cherfi", "Aki Salabee", "Stéphane Fernandez", "Samuel Granier", "Simon Reis", "François De La Bourdonnaye", "Flo Arnauduc", "Luka Brunel", "Hakim Cherfi", "Milan Couzin", "Yoann Canal"]'::jsonb),
    ('872aea7f-d3ef-4406-ada2-f7c56acf6e3b'::uuid, date '2025-04-10', '4-1-4-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Julien Cesar", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 30, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 70, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Aki Salabee", "is_gk": false, "x_pct": 50, "y_pct": 52.1, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Simon Reis", "is_gk": false, "x_pct": 10, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 33, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 67, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Mehdi Liauzun", "is_gk": false, "x_pct": 90, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '[]'::jsonb, '["Samih Châa", "Julien Cesar", "Stéphane Fernandez", "Olivier Millet", "Samuel Granier", "Aki Salabee", "Simon Reis", "Flo Arnauduc", "Luka Brunel", "Mehdi Liauzun", "Milan Couzin"]'::jsonb),
    ('ab9c801f-bf53-4e69-9854-6fbdf5eeb272'::uuid, date '2025-05-06', '4-1-4-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Alyoun Cherfi", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 30, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Olivier Millet", "is_gk": false, "x_pct": 70, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 50, "y_pct": 52.1, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 10, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 33, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 67, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Hakim Cherfi", "is_gk": false, "x_pct": 90, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '[]'::jsonb, '["Samih Châa", "Alyoun Cherfi", "Stéphane Fernandez", "Olivier Millet", "Samuel Granier", "Flo Arnauduc", "Hakim Cherfi", "Milan Couzin"]'::jsonb),
    ('587f81ce-002f-4bbe-88f0-ff1a5164fba6'::uuid, date '2025-10-16', '4-1-4-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Aki Salabee", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 30, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 70, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Poste laissé vide", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 50, "y_pct": 52.1, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "François De La Bourdonnaye", "is_gk": false, "x_pct": 10, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 33, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Alban Ricard", "is_gk": false, "x_pct": 67, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Allan Bamokena", "is_gk": false, "x_pct": 90, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '[]'::jsonb, '["Samih Châa", "Aki Salabee", "Stéphane Fernandez", "Samuel Granier", "Flo Arnauduc", "François De La Bourdonnaye", "Luka Brunel", "Alban Ricard", "Allan Bamokena", "Milan Couzin"]'::jsonb),
    ('f8b08383-42ad-4ba8-939d-d779f2ccc753'::uuid, date '2025-11-03', '4-1-4-1', '[{"name": "Samih Châa", "is_gk": true, "x_pct": 50, "y_pct": 93.5, "position_code": "GDB", "position_label": "Gardien"}, {"name": "Alyoun Cherfi", "is_gk": false, "x_pct": 10, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Stéphane Fernandez", "is_gk": false, "x_pct": 30, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Samuel Granier", "is_gk": false, "x_pct": 70, "y_pct": 74.8, "position_code": "DEC", "position_label": "Défenseur central"}, {"name": "Julio Vignard", "is_gk": false, "x_pct": 90, "y_pct": 68.5, "position_code": "ARL", "position_label": "Arrière latéral"}, {"name": "Flo Arnauduc", "is_gk": false, "x_pct": 50, "y_pct": 52.1, "position_code": "MDE", "position_label": "Milieu défensif"}, {"name": "Nicolas Belmonte", "is_gk": false, "x_pct": 10, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Luka Brunel", "is_gk": false, "x_pct": 33, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Alban Ricard", "is_gk": false, "x_pct": 67, "y_pct": 30.2, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Allan Bamokena", "is_gk": false, "x_pct": 90, "y_pct": 23.8, "position_code": "MOF", "position_label": "Milieu offensif"}, {"name": "Milan Couzin", "is_gk": false, "x_pct": 50, "y_pct": 5, "position_code": "AVC", "position_label": "Avant-centre"}]'::jsonb, '["Hakim Cherfi", "Aki Salabee", "Anis Messaoudi"]'::jsonb, '["Samih Châa", "Alyoun Cherfi", "Stéphane Fernandez", "Samuel Granier", "Julio Vignard", "Flo Arnauduc", "Nicolas Belmonte", "Luka Brunel", "Alban Ricard", "Allan Bamokena", "Milan Couzin", "Hakim Cherfi", "Aki Salabee", "Anis Messaoudi"]'::jsonb)
    ) as t(match_id, match_date, formation, field_players, bench_players, placed_names)
  loop
    select d.present_names into v_present
    from public.historical_match_details d
    join public.historical_match_scores s on s.id = d.match_id
    where d.match_id = v_row.match_id
      and s.match_date = v_row.match_date
      and coalesce(jsonb_array_length(d.field_players), 0) = 0
    for update of d;

    if not found then
      continue;
    end if;

    select coalesce(array_agg(n order by n), '{}') into v_expected
    from jsonb_array_elements_text(v_present) as p(n)
    where n <> 'Philippe Couzin';

    select coalesce(array_agg(n order by n), '{}') into v_placed
    from jsonb_array_elements_text(v_row.placed_names) as p(n);

    if v_expected is distinct from v_placed then
      raise exception 'Composition reconstituée incohérente pour le match du % : présents % / placés %',
        v_row.match_date, v_expected, v_placed;
    end if;

    update public.historical_match_details
    set formation = v_row.formation,
        field_players = v_row.field_players,
        bench_players = v_row.bench_players
    where match_id = v_row.match_id;
  end loop;
end
$$;

commit;
