-- Bug 15 : les references d'incident ne menent nulle part.
--
-- L'application affiche « Référence : ASG-20260813-084417-001 » et invite a la
-- communiquer au support, mais la journalisation passait uniquement par
-- `dart:developer.log()`, qui n'emet rien dans un build web release. La
-- reference n'existait donc nulle part ailleurs, et la procedure decrite dans
-- docs/observability.md (« rechercher incident=<reference> dans les journaux »)
-- etait inoperante.
--
-- Les incidents sont desormais collectes cote serveur. Comme le format texte
-- d'origine, l'enregistrement ne contient JAMAIS le message de l'erreur :
-- seulement l'operation, le type d'erreur, la version de l'application et la
-- reference.

begin;

create table if not exists private.client_incident_log (
  id bigint generated by default as identity primary key,
  reference text not null,
  operation text not null,
  error_type text not null,
  app_version text not null,
  profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

comment on table private.client_incident_log is
  'Incidents remontes par l application cliente. Ne contient aucun message d erreur ni donnee personnelle : uniquement operation, type d erreur, version et reference support.';

create index if not exists client_incident_log_reference_idx
  on private.client_incident_log (reference);
create index if not exists client_incident_log_created_at_idx
  on private.client_incident_log (created_at desc);

-- Schema `private` : jamais expose par PostgREST, et refus par defaut.
alter table private.client_incident_log enable row level security;

-- Purge automatique : un journal d incidents n a pas vocation a etre conserve
-- indefiniment.
create or replace function private.purge_client_incident_log(
  p_now timestamptz default now()
)
returns integer
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_deleted integer := 0;
begin
  delete from private.client_incident_log
  where created_at < p_now - interval '90 days';
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$function$;

revoke all on function private.purge_client_incident_log(timestamptz)
  from public, anon, authenticated;

-- Point d entree de l application. Limite volontairement stricte : un client
-- en boucle d erreur ne doit pas pouvoir inonder la table.
create or replace function public.log_client_incident(
  p_reference text,
  p_operation text,
  p_error_type text,
  p_app_version text
)
returns void
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_actor uuid := (select auth.uid());
  v_recent integer;
begin
  if v_actor is null then
    return;
  end if;
  if nullif(btrim(p_reference), '') is null then
    return;
  end if;

  select count(*)
  into v_recent
  from private.client_incident_log entry
  where entry.profile_id = v_actor
    and entry.created_at > now() - interval '1 minute';

  if v_recent >= 20 then
    return;
  end if;

  insert into private.client_incident_log (
    reference, operation, error_type, app_version, profile_id
  )
  values (
    left(btrim(p_reference), 64),
    left(coalesce(nullif(btrim(p_operation), ''), 'unknown'), 128),
    left(coalesce(nullif(btrim(p_error_type), ''), 'unknown'), 128),
    left(coalesce(nullif(btrim(p_app_version), ''), 'unknown'), 32),
    v_actor
  );
end;
$function$;

comment on function public.log_client_incident(text, text, text, text) is
  'Enregistre un incident client (operation, type d erreur, version, reference). Aucun message d erreur n est transmis. Limite a 20 evenements par minute et par compte.';

revoke all on function public.log_client_incident(text, text, text, text)
  from public, anon;
grant execute on function public.log_client_incident(text, text, text, text)
  to authenticated, service_role;

-- Consultation reservee au staff.
create or replace function public.admin_recent_client_incidents(
  p_limit integer default 100
)
returns table(
  reference text,
  operation text,
  error_type text,
  app_version text,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path to ''
as $function$
begin
  if not public.is_match_staff() then
    raise exception 'Active administrator role required' using errcode = '42501';
  end if;

  return query
  select entry.reference, entry.operation, entry.error_type,
         entry.app_version, entry.created_at
  from private.client_incident_log entry
  order by entry.created_at desc
  limit least(greatest(coalesce(p_limit, 100), 1), 500);
end;
$function$;

revoke all on function public.admin_recent_client_incidents(integer)
  from public, anon;
grant execute on function public.admin_recent_client_incidents(integer)
  to authenticated, service_role;

commit;
