begin;

create table private.profile_badge_audit_log (
  id bigint generated by default as identity primary key,
  profile_id uuid not null,
  profile_label text not null,
  badge_id uuid not null,
  badge_code text not null,
  badge_name text not null,
  action text not null check (action in ('award', 'revoke')),
  actor_profile_id uuid not null,
  actor_label text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table private.profile_badge_audit_log is
  'Append-only audit trail for staff badge awards and revocations.';

revoke all on table private.profile_badge_audit_log
  from public, anon, authenticated;
grant select on table private.profile_badge_audit_log to service_role;

create or replace function private.reject_profile_badge_audit_mutation()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  raise exception 'Badge audit log is append-only' using errcode = '55000';
end;
$function$;

revoke all on function private.reject_profile_badge_audit_mutation()
  from public, anon, authenticated;

create trigger trg_profile_badge_audit_append_only
before update or delete on private.profile_badge_audit_log
for each row execute function private.reject_profile_badge_audit_mutation();

-- Preserve the manual assignments that still exist today. Historical revoked
-- assignments cannot be reconstructed reliably, so the trail is complete from
-- this migration onward and explicitly marks these initial rows as backfilled.
insert into private.profile_badge_audit_log (
  profile_id,
  profile_label,
  badge_id,
  badge_code,
  badge_name,
  action,
  actor_profile_id,
  actor_label,
  metadata,
  created_at
)
select
  pb.profile_id,
  coalesce(
    nullif(btrim(target.surnom), ''),
    nullif(btrim(target.first_name), ''),
    pb.profile_id::text
  ),
  pb.badge_id,
  badge.code,
  badge.name,
  'award',
  pb.awarded_by,
  coalesce(
    nullif(btrim(actor.surnom), ''),
    nullif(btrim(actor.first_name), ''),
    pb.awarded_by::text
  ),
  jsonb_build_object('backfilled', true, 'source', 'profile_badges'),
  pb.awarded_at
from public.profile_badges pb
join public.badges badge on badge.id = pb.badge_id
join public.profiles target on target.id = pb.profile_id
left join public.profiles actor on actor.id = pb.awarded_by
where pb.source = 'manual'
  and pb.awarded_by is not null;

create or replace function public.staff_award_badge(
  p_profile_id uuid,
  p_badge_code text
)
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_badge_id uuid;
  v_badge_name text;
  v_profile_label text;
  v_actor_id uuid := auth.uid();
  v_actor_label text;
  v_previous_source text;
begin
  if not public.is_moderator() then
    raise exception 'Moderator role required' using errcode = '42501';
  end if;

  select id, name
  into v_badge_id, v_badge_name
  from public.badges
  where code = p_badge_code;

  if not found then
    raise exception 'Unknown badge' using errcode = '22023';
  end if;

  select coalesce(
    nullif(btrim(p.surnom), ''),
    nullif(btrim(p.first_name), ''),
    p.id::text
  )
  into v_profile_label
  from public.profiles p
  where p.id = p_profile_id;

  if not found then
    raise exception 'Unknown profile' using errcode = '22023';
  end if;

  if p_badge_code = 'role_goalkeeper'
     and not exists (
       select 1
       from public.profiles p
       where p.id = p_profile_id
         and p.is_goalkeeper is true
     ) then
    raise exception 'Goalkeeper badge can only be awarded to a goalkeeper'
      using errcode = '22023';
  end if;

  select pb.source
  into v_previous_source
  from public.profile_badges pb
  where pb.profile_id = p_profile_id
    and pb.badge_id = v_badge_id;

  select coalesce(
    nullif(btrim(p.surnom), ''),
    nullif(btrim(p.first_name), ''),
    v_actor_id::text
  )
  into v_actor_label
  from public.profiles p
  where p.id = v_actor_id;

  if v_actor_label is null then
    v_actor_label := v_actor_id::text;
  end if;

  insert into public.profile_badges(profile_id, badge_id, source, awarded_by)
  values (p_profile_id, v_badge_id, 'manual', v_actor_id)
  on conflict (profile_id, badge_id)
  do update set
    source = 'manual',
    awarded_by = v_actor_id,
    awarded_at = now();

  insert into private.profile_badge_audit_log (
    profile_id,
    profile_label,
    badge_id,
    badge_code,
    badge_name,
    action,
    actor_profile_id,
    actor_label,
    metadata
  ) values (
    p_profile_id,
    v_profile_label,
    v_badge_id,
    p_badge_code,
    v_badge_name,
    'award',
    v_actor_id,
    v_actor_label,
    jsonb_build_object('previous_source', v_previous_source)
  );

  return true;
end;
$function$;

create or replace function public.staff_revoke_badge(
  p_profile_id uuid,
  p_badge_code text
)
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_badge_id uuid;
  v_badge_name text;
  v_profile_label text;
  v_actor_id uuid := auth.uid();
  v_actor_label text;
  v_previous_source text;
begin
  if not public.is_moderator() then
    raise exception 'Moderator role required' using errcode = '42501';
  end if;

  select id, name
  into v_badge_id, v_badge_name
  from public.badges
  where code = p_badge_code;

  if not found then
    raise exception 'Unknown badge' using errcode = '22023';
  end if;

  select coalesce(
    nullif(btrim(p.surnom), ''),
    nullif(btrim(p.first_name), ''),
    p.id::text
  )
  into v_profile_label
  from public.profiles p
  where p.id = p_profile_id;

  if not found then
    raise exception 'Unknown profile' using errcode = '22023';
  end if;

  select coalesce(
    nullif(btrim(p.surnom), ''),
    nullif(btrim(p.first_name), ''),
    v_actor_id::text
  )
  into v_actor_label
  from public.profiles p
  where p.id = v_actor_id;

  if v_actor_label is null then
    v_actor_label := v_actor_id::text;
  end if;

  delete from public.profile_badges
  where profile_id = p_profile_id
    and badge_id = v_badge_id
  returning source into v_previous_source;

  if found then
    insert into private.profile_badge_audit_log (
      profile_id,
      profile_label,
      badge_id,
      badge_code,
      badge_name,
      action,
      actor_profile_id,
      actor_label,
      metadata
    ) values (
      p_profile_id,
      v_profile_label,
      v_badge_id,
      p_badge_code,
      v_badge_name,
      'revoke',
      v_actor_id,
      v_actor_label,
      jsonb_build_object('previous_source', v_previous_source)
    );
  end if;

  perform public.recalculate_profile_badges(p_profile_id);
  return true;
end;
$function$;

revoke all on function public.staff_award_badge(uuid, text) from public, anon;
revoke all on function public.staff_revoke_badge(uuid, text) from public, anon;
grant execute on function public.staff_award_badge(uuid, text)
  to authenticated, service_role;
grant execute on function public.staff_revoke_badge(uuid, text)
  to authenticated, service_role;

commit;
