-- Catalogue officiel des 220 badges (Phase 1 : définitions).
-- Modèle uniforme : chaque badge est un palier (metric, threshold).
-- Le moteur d'attribution et les métriques sont (re)construits aux phases suivantes.

delete from public.profile_badges where source = 'auto';
delete from public.badges;

insert into public.badges(code, name, description, emoji, family, category, kind, auto, metric, threshold, sort_order) values
('matches_played_season__1','Première feuille','1 match joué sur une saison','👕','joueur','joueur_saison','tier',true,'matches_played_season',1,1),
('matches_played_season__5','Dans la rotation','5 matchs joués sur une saison','👕','joueur','joueur_saison','tier',true,'matches_played_season',5,2),
('matches_played_season__10','Régulier','10 matchs joués sur une saison','👕','joueur','joueur_saison','tier',true,'matches_played_season',10,3),
('matches_played_season__15','Cadre','15 matchs joués sur une saison','👕','joueur','joueur_saison','tier',true,'matches_played_season',15,4),
('matches_played_season__20','Indispensable','20 matchs joués sur une saison','👕','joueur','joueur_saison','tier',true,'matches_played_season',20,5),
('matches_played_season__25','Pilier de la saison','25 matchs joués sur une saison','👕','joueur','joueur_saison','tier',true,'matches_played_season',25,6),
('matches_played_season__30','Cap des 30','30 matchs joués sur une saison','👕','joueur','joueur_saison','tier',true,'matches_played_season',30,7),
('wins_season__1','Première victoire','1 victoire sur une saison','🏆','joueur','joueur_saison','tier',true,'wins_season',1,8),
('wins_season__5','Gagnant','5 victoires sur une saison','🏆','joueur','joueur_saison','tier',true,'wins_season',5,9),
('wins_season__10','Serial Winner','10 victoires sur une saison','🏆','joueur','joueur_saison','tier',true,'wins_season',10,10),
('wins_season__15','Machine à gagner','15 victoires sur une saison','🏆','joueur','joueur_saison','tier',true,'wins_season',15,11),
('wins_season__20','Saison de champion','20 victoires sur une saison','🏆','joueur','joueur_saison','tier',true,'wins_season',20,12),
('goals_season__1','Premier but','1 but sur une saison','⚽','joueur','joueur_saison','tier',true,'goals_season',1,13),
('goals_season__5','Buteur','5 buts sur une saison','⚽','joueur','joueur_saison','tier',true,'goals_season',5,14),
('goals_season__10','Gâchette','10 buts sur une saison','⚽','joueur','joueur_saison','tier',true,'goals_season',10,15),
('goals_season__15','Canonnier','15 buts sur une saison','⚽','joueur','joueur_saison','tier',true,'goals_season',15,16),
('goals_season__20','Machine à buts','20 buts sur une saison','⚽','joueur','joueur_saison','tier',true,'goals_season',20,17),
('goals_season__25','Serial buteur','25 buts sur une saison','⚽','joueur','joueur_saison','tier',true,'goals_season',25,18),
('goals_season__30','Saison historique','30 buts sur une saison','⚽','joueur','joueur_saison','tier',true,'goals_season',30,19),
('mvp_season__1','Premier HDM','1 homme du match sur une saison','⭐','joueur','joueur_saison','tier',true,'mvp_season',1,20),
('mvp_season__3','Patron','3 hommes du match sur une saison','⭐','joueur','joueur_saison','tier',true,'mvp_season',3,21),
('mvp_season__5','Boss','5 hommes du match sur une saison','⭐','joueur','joueur_saison','tier',true,'mvp_season',5,22),
('mvp_season__7','Intouchable','7 hommes du match sur une saison','⭐','joueur','joueur_saison','tier',true,'mvp_season',7,23),
('mvp_season__10','Roi de la saison','10 hommes du match sur une saison','⭐','joueur','joueur_saison','tier',true,'mvp_season',10,24),
('clean_sheets_season__1','Premier clean sheet','1 clean sheet sur une saison','🧤','joueur','joueur_saison','tier',true,'clean_sheets_season',1,25),
('clean_sheets_season__3','Rempart','3 clean sheets sur une saison','🧤','joueur','joueur_saison','tier',true,'clean_sheets_season',3,26),
('clean_sheets_season__5','Mur','5 clean sheets sur une saison','🧤','joueur','joueur_saison','tier',true,'clean_sheets_season',5,27),
('clean_sheets_season__7','Forteresse','7 clean sheets sur une saison','🧤','joueur','joueur_saison','tier',true,'clean_sheets_season',7,28),
('clean_sheets_season__10','Infranchissable','10 clean sheets sur une saison','🧤','joueur','joueur_saison','tier',true,'clean_sheets_season',10,29),
('matches_played__25','Habitué','25 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',25,30),
('matches_played__50','Fidèle','50 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',50,31),
('matches_played__100','Centurion','100 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',100,32),
('matches_played__150','Pilier','150 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',150,33),
('matches_played__200','Monument','200 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',200,34),
('matches_played__250','Légende','250 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',250,35),
('matches_played__300','Mythe','300 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',300,36),
('matches_played__350','Éternel','350 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',350,37),
('matches_played__400','Immortel','400 matchs en carrière','👕','joueur','joueur_all_time','tier',true,'matches_played',400,38),
('wins__25','Gagnant confirmé','25 victoires en carrière','🏆','joueur','joueur_all_time','tier',true,'wins',25,39),
('wins__50','Serial Winner','50 victoires en carrière','🏆','joueur','joueur_all_time','tier',true,'wins',50,40),
('wins__100','Machine à gagner','100 victoires en carrière','🏆','joueur','joueur_all_time','tier',true,'wins',100,41),
('wins__150','Maître de la victoire','150 victoires en carrière','🏆','joueur','joueur_all_time','tier',true,'wins',150,42),
('wins__200','Légende victorieuse','200 victoires en carrière','🏆','joueur','joueur_all_time','tier',true,'wins',200,43),
('wins__250','Dominateur','250 victoires en carrière','🏆','joueur','joueur_all_time','tier',true,'wins',250,44),
('wins__300','Empereur de la victoire','300 victoires en carrière','🏆','joueur','joueur_all_time','tier',true,'wins',300,45),
('goals__10','Buteur confirmé','10 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',10,46),
('goals__25','Canonnier','25 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',25,47),
('goals__50','Gâchette historique','50 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',50,48),
('goals__100','Club des 100','100 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',100,49),
('goals__150','Légende du but','150 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',150,50),
('goals__200','Extraterrestre','200 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',200,51),
('goals__250','Monstre','250 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',250,52),
('goals__300','Roi des buteurs','300 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',300,53),
('goals__400','Immortel du but','400 buts en carrière','⚽','joueur','joueur_all_time','tier',true,'goals',400,54),
('doubles__1','Premier doublé','1 doublé (2 buts dans un match)','🎯','joueur','joueur_all_time','tier',true,'doubles',1,55),
('doubles__5','Habitué du doublé','5 doublés','🎯','joueur','joueur_all_time','tier',true,'doubles',5,56),
('doubles__10','Spécialiste du doublé','10 doublés','🎯','joueur','joueur_all_time','tier',true,'doubles',10,57),
('doubles__15','Machine à doublés','15 doublés','🎯','joueur','joueur_all_time','tier',true,'doubles',15,58),
('doubles__20','Maître du doublé','20 doublés','🎯','joueur','joueur_all_time','tier',true,'doubles',20,59),
('doubles__25','Roi du doublé','25 doublés','🎯','joueur','joueur_all_time','tier',true,'doubles',25,60),
('doubles__30','Légende des doublés','30 doublés','🎯','joueur','joueur_all_time','tier',true,'doubles',30,61),
('hattricks__1','Premier triplé','1 triplé (3 buts ou plus dans un match)','🎩','joueur','joueur_all_time','tier',true,'hattricks',1,62),
('hattricks__3','Habitué du triplé','3 triplés','🎩','joueur','joueur_all_time','tier',true,'hattricks',3,63),
('hattricks__5','Spécialiste du triplé','5 triplés','🎩','joueur','joueur_all_time','tier',true,'hattricks',5,64),
('hattricks__10','Machine à triplés','10 triplés','🎩','joueur','joueur_all_time','tier',true,'hattricks',10,65),
('hattricks__15','Roi du triplé','15 triplés','🎩','joueur','joueur_all_time','tier',true,'hattricks',15,66),
('hattricks__20','Légende des triplés','20 triplés','🎩','joueur','joueur_all_time','tier',true,'hattricks',20,67),
('mvp__5','Patron','5 hommes du match en carrière','⭐','joueur','joueur_all_time','tier',true,'mvp',5,68),
('mvp__10','Boss','10 hommes du match en carrière','⭐','joueur','joueur_all_time','tier',true,'mvp',10,69),
('mvp__20','Roi des HDM','20 hommes du match en carrière','⭐','joueur','joueur_all_time','tier',true,'mvp',20,70),
('mvp__30','Icône','30 hommes du match en carrière','⭐','joueur','joueur_all_time','tier',true,'mvp',30,71),
('mvp__40','Légende des HDM','40 hommes du match en carrière','⭐','joueur','joueur_all_time','tier',true,'mvp',40,72),
('mvp__50','Mythe des HDM','50 hommes du match en carrière','⭐','joueur','joueur_all_time','tier',true,'mvp',50,73),
('mvp__75','Inoubliable','75 hommes du match en carrière','⭐','joueur','joueur_all_time','tier',true,'mvp',75,74),
('mvp__100','Éternel homme du match','100 hommes du match en carrière','⭐','joueur','joueur_all_time','tier',true,'mvp',100,75),
('clean_sheets__5','Rempart','5 clean sheets en carrière','🧤','joueur','joueur_all_time','tier',true,'clean_sheets',5,76),
('clean_sheets__10','Mur','10 clean sheets en carrière','🧤','joueur','joueur_all_time','tier',true,'clean_sheets',10,77),
('clean_sheets__20','Forteresse','20 clean sheets en carrière','🧤','joueur','joueur_all_time','tier',true,'clean_sheets',20,78),
('clean_sheets__30','Infranchissable','30 clean sheets en carrière','🧤','joueur','joueur_all_time','tier',true,'clean_sheets',30,79),
('clean_sheets__40','Gardien d’exception','40 clean sheets en carrière','🧤','joueur','joueur_all_time','tier',true,'clean_sheets',40,80),
('clean_sheets__50','Gardien légendaire','50 clean sheets en carrière','🧤','joueur','joueur_all_time','tier',true,'clean_sheets',50,81),
('clean_sheets__75','Mur éternel','75 clean sheets en carrière','🧤','joueur','joueur_all_time','tier',true,'clean_sheets',75,82),
('pred_validated_season__1','Premier prono','1 prono validé sur une saison','📝','pronostiqueur','pronos_saison','tier',true,'pred_validated_season',1,83),
('pred_validated_season__5','Pronostiqueur régulier','5 pronos sur une saison','📝','pronostiqueur','pronos_saison','tier',true,'pred_validated_season',5,84),
('pred_validated_season__10','Assidu','10 pronos sur une saison','📝','pronostiqueur','pronos_saison','tier',true,'pred_validated_season',10,85),
('pred_validated_season__15','Mi-saison','15 pronos sur une saison','📝','pronostiqueur','pronos_saison','tier',true,'pred_validated_season',15,86),
('pred_validated_season__20','Incontournable','20 pronos sur une saison','📝','pronostiqueur','pronos_saison','tier',true,'pred_validated_season',20,87),
('pred_validated_season__25','Marathonien','25 pronos sur une saison','📝','pronostiqueur','pronos_saison','tier',true,'pred_validated_season',25,88),
('pred_validated_season__30','Cap des 30 pronos','30 pronos sur une saison','📝','pronostiqueur','pronos_saison','tier',true,'pred_validated_season',30,89),
('pred_good_result_season__5','Bon œil','5 bonnes issues sur une saison','🎯','pronostiqueur','pronos_saison','tier',true,'pred_good_result_season',5,90),
('pred_good_result_season__10','Connaisseur','10 bonnes issues sur une saison','🎯','pronostiqueur','pronos_saison','tier',true,'pred_good_result_season',10,91),
('pred_good_result_season__15','Expert','15 bonnes issues sur une saison','🎯','pronostiqueur','pronos_saison','tier',true,'pred_good_result_season',15,92),
('pred_good_result_season__20','Maître du résultat','20 bonnes issues sur une saison','🎯','pronostiqueur','pronos_saison','tier',true,'pred_good_result_season',20,93),
('pred_good_result_season__25','Oracle des résultats','25 bonnes issues sur une saison','🎯','pronostiqueur','pronos_saison','tier',true,'pred_good_result_season',25,94),
('pred_good_result_season__30','Grand maître','30 bonnes issues sur une saison','🎯','pronostiqueur','pronos_saison','tier',true,'pred_good_result_season',30,95),
('pred_exact_score_season__1','Premier exact','1 score exact sur une saison','🔬','pronostiqueur','pronos_saison','tier',true,'pred_exact_score_season',1,96),
('pred_exact_score_season__3','Chirurgien','3 scores exacts sur une saison','🔬','pronostiqueur','pronos_saison','tier',true,'pred_exact_score_season',3,97),
('pred_exact_score_season__5','Sniper','5 scores exacts sur une saison','🔬','pronostiqueur','pronos_saison','tier',true,'pred_exact_score_season',5,98),
('pred_exact_score_season__7','Oracle','7 scores exacts sur une saison','🔬','pronostiqueur','pronos_saison','tier',true,'pred_exact_score_season',7,99),
('pred_exact_score_season__10','Prophète','10 scores exacts sur une saison','🔬','pronostiqueur','pronos_saison','tier',true,'pred_exact_score_season',10,100),
('pred_player_exact_season__1','Premier visionnaire','1 prono joueur exact sur une saison','🔮','pronostiqueur','pronos_saison','tier',true,'pred_player_exact_season',1,101),
('pred_player_exact_season__3','Visionnaire','3 pronos joueurs exacts sur une saison','🔮','pronostiqueur','pronos_saison','tier',true,'pred_player_exact_season',3,102),
('pred_player_exact_season__5','Grand visionnaire','5 pronos joueurs exacts sur une saison','🔮','pronostiqueur','pronos_saison','tier',true,'pred_player_exact_season',5,103),
('pred_player_exact_season__10','Prophète des joueurs','10 pronos joueurs exacts sur une saison','🔮','pronostiqueur','pronos_saison','tier',true,'pred_player_exact_season',10,104),
('pred_player_exact_season__15','Vision absolue','15 pronos joueurs exacts sur une saison','🔮','pronostiqueur','pronos_saison','tier',true,'pred_player_exact_season',15,105),
('pred_validated__1','Premier prono historique','1 prono validé en carrière','📝','pronostiqueur','pronos_all_time','tier',true,'pred_validated',1,106),
('pred_validated__10','Apprenti pronostiqueur','10 pronos validés en carrière','📝','pronostiqueur','pronos_all_time','tier',true,'pred_validated',10,107),
('pred_validated__25','Pronostiqueur confirmé','25 pronos validés en carrière','📝','pronostiqueur','pronos_all_time','tier',true,'pred_validated',25,108),
('pred_validated__50','Vétéran des pronos','50 pronos validés en carrière','📝','pronostiqueur','pronos_all_time','tier',true,'pred_validated',50,109),
('pred_validated__100','Centurion des pronos','100 pronos validés en carrière','📝','pronostiqueur','pronos_all_time','tier',true,'pred_validated',100,110),
('pred_validated__200','Expert historique','200 pronos validés en carrière','📝','pronostiqueur','pronos_all_time','tier',true,'pred_validated',200,111),
('pred_good_result__1','Premier bon résultat','1 bonne issue en carrière','🎯','pronostiqueur','pronos_all_time','tier',true,'pred_good_result',1,112),
('pred_good_result__10','Bon œil historique','10 bonnes issues en carrière','🎯','pronostiqueur','pronos_all_time','tier',true,'pred_good_result',10,113),
('pred_good_result__25','Parieur avisé','25 bonnes issues en carrière','🎯','pronostiqueur','pronos_all_time','tier',true,'pred_good_result',25,114),
('pred_good_result__50','Connaisseur confirmé','50 bonnes issues en carrière','🎯','pronostiqueur','pronos_all_time','tier',true,'pred_good_result',50,115),
('pred_good_result__100','Expert All Time','100 bonnes issues en carrière','🎯','pronostiqueur','pronos_all_time','tier',true,'pred_good_result',100,116),
('pred_good_result__200','Maître des résultats','200 bonnes issues en carrière','🎯','pronostiqueur','pronos_all_time','tier',true,'pred_good_result',200,117),
('pred_exact_score__5','Œil de lynx','5 scores exacts en carrière','🔬','pronostiqueur','pronos_all_time','tier',true,'pred_exact_score',5,118),
('pred_exact_score__10','Devin','10 scores exacts en carrière','🔬','pronostiqueur','pronos_all_time','tier',true,'pred_exact_score',10,119),
('pred_exact_score__25','Sniper historique','25 scores exacts en carrière','🔬','pronostiqueur','pronos_all_time','tier',true,'pred_exact_score',25,120),
('pred_exact_score__50','Grand oracle','50 scores exacts en carrière','🔬','pronostiqueur','pronos_all_time','tier',true,'pred_exact_score',50,121),
('pred_exact_score__100','Prophète','100 scores exacts en carrière','🔬','pronostiqueur','pronos_all_time','tier',true,'pred_exact_score',100,122),
('pred_player_exact__5','Visionnaire confirmé','5 pronos joueurs exacts en carrière','🔮','pronostiqueur','pronos_all_time','tier',true,'pred_player_exact',5,123),
('pred_player_exact__10','Devin des joueurs','10 pronos joueurs exacts en carrière','🔮','pronostiqueur','pronos_all_time','tier',true,'pred_player_exact',10,124),
('pred_player_exact__25','Expert des joueurs','25 pronos joueurs exacts en carrière','🔮','pronostiqueur','pronos_all_time','tier',true,'pred_player_exact',25,125),
('pred_player_exact__50','Oracle des joueurs','50 pronos joueurs exacts en carrière','🔮','pronostiqueur','pronos_all_time','tier',true,'pred_player_exact',50,126),
('pred_player_exact__100','Prophète des joueurs','100 pronos joueurs exacts en carrière','🔮','pronostiqueur','pronos_all_time','tier',true,'pred_player_exact',100,127),
('seasons_complete__1','Saison complète','Tous les matchs réels d’une saison joués','📅','joueur','palmares','tier',true,'seasons_complete',1,128),
('seasons_complete__2','Fidélité totale','2 saisons complètes','📅','joueur','palmares','tier',true,'seasons_complete',2,129),
('seasons_complete__3','Toujours présent','3 saisons complètes','📅','joueur','palmares','tier',true,'seasons_complete',3,130),
('seasons_complete__4','Présence absolue','4 saisons complètes','📅','joueur','palmares','tier',true,'seasons_complete',4,131),
('seasons_complete__5','Inusable de saison','5 saisons complètes','📅','joueur','palmares','tier',true,'seasons_complete',5,132),
('seasons_pred_complete__1','Prono complet','Tous les matchs réels d’une saison pronostiqués','🗓️','pronostiqueur','palmares','tier',true,'seasons_pred_complete',1,133),
('seasons_pred_complete__2','Double prono complet','2 saisons intégralement pronostiquées','🗓️','pronostiqueur','palmares','tier',true,'seasons_pred_complete',2,134),
('seasons_pred_complete__3','Assiduité parfaite','3 saisons intégralement pronostiquées','🗓️','pronostiqueur','palmares','tier',true,'seasons_pred_complete',3,135),
('seasons_pred_complete__4','Quadruple prono complet','4 saisons intégralement pronostiquées','🗓️','pronostiqueur','palmares','tier',true,'seasons_pred_complete',4,136),
('seasons_pred_complete__5','Éternel pronostiqueur','5 saisons intégralement pronostiquées','🗓️','pronostiqueur','palmares','tier',true,'seasons_pred_complete',5,137),
('seasons_perfect__1','100 %','Une saison entière pronostiquée avec la bonne issue','💯','pronostiqueur','palmares','tier',true,'seasons_perfect',1,138),
('seasons_perfect__2','Double perfection','2 saisons parfaites','💯','pronostiqueur','palmares','tier',true,'seasons_perfect',2,139),
('seasons_perfect__3','Perfection absolue','3 saisons parfaites','💯','pronostiqueur','palmares','tier',true,'seasons_perfect',3,140),
('title_top_scorer__1','Meilleur buteur','1 titre','👑','joueur','palmares','tier',true,'title_top_scorer',1,141),
('title_top_scorer__2','Double meilleur buteur','2 titres','👑','joueur','palmares','tier',true,'title_top_scorer',2,142),
('title_top_scorer__3','Triple meilleur buteur','3 titres','👑','joueur','palmares','tier',true,'title_top_scorer',3,143),
('title_top_scorer__4','Quadruple meilleur buteur','4 titres','👑','joueur','palmares','tier',true,'title_top_scorer',4,144),
('title_top_scorer__5','Quintuple meilleur buteur','5 titres','👑','joueur','palmares','tier',true,'title_top_scorer',5,145),
('title_top_scorer__6','Sextuple meilleur buteur','6 titres','👑','joueur','palmares','tier',true,'title_top_scorer',6,146),
('title_top_scorer__7','Septuple meilleur buteur','7 titres','👑','joueur','palmares','tier',true,'title_top_scorer',7,147),
('title_top_scorer__8','Octuple meilleur buteur','8 titres','👑','joueur','palmares','tier',true,'title_top_scorer',8,148),
('title_top_scorer__9','Nonuple meilleur buteur','9 titres','👑','joueur','palmares','tier',true,'title_top_scorer',9,149),
('title_top_scorer__10','Décennie des buteurs','10 titres','👑','joueur','palmares','tier',true,'title_top_scorer',10,150),
('title_worst_scorer__1','Moins bon buteur','1 titre','🥴','joueur','palmares','tier',true,'title_worst_scorer',1,151),
('title_worst_scorer__2','Double lanterne offensive','2 titres','🥴','joueur','palmares','tier',true,'title_worst_scorer',2,152),
('title_worst_scorer__3','Abonné au minimum','3 titres','🥴','joueur','palmares','tier',true,'title_worst_scorer',3,153),
('title_worst_scorer__4','Quadruple lanterne offensive','4 titres','🥴','joueur','palmares','tier',true,'title_worst_scorer',4,154),
('title_worst_scorer__5','Légende à l’envers','5 titres','🥴','joueur','palmares','tier',true,'title_worst_scorer',5,155),
('title_most_present__1','Plus présent','1 titre','📌','joueur','palmares','tier',true,'title_most_present',1,156),
('title_most_present__2','Fidèle parmi les fidèles','2 titres','📌','joueur','palmares','tier',true,'title_most_present',2,157),
('title_most_present__3','Toujours là','3 titres','📌','joueur','palmares','tier',true,'title_most_present',3,158),
('title_most_present__4','Présence dominante','4 titres','📌','joueur','palmares','tier',true,'title_most_present',4,159),
('title_most_present__5','Roi de l’assiduité','5 titres','📌','joueur','palmares','tier',true,'title_most_present',5,160),
('title_least_present__1','Moins présent','1 titre','👻','joueur','palmares','tier',true,'title_least_present',1,161),
('title_least_present__2','Absent récidiviste','2 titres','👻','joueur','palmares','tier',true,'title_least_present',2,162),
('title_least_present__3','Joueur fantôme','3 titres','👻','joueur','palmares','tier',true,'title_least_present',3,163),
('title_least_present__4','Absent chronique','4 titres','👻','joueur','palmares','tier',true,'title_least_present',4,164),
('title_least_present__5','Porté disparu','5 titres','👻','joueur','palmares','tier',true,'title_least_present',5,165),
('title_mvp_king__1','Roi des HDM','1 titre','⭐','joueur','palmares','tier',true,'title_mvp_king',1,166),
('title_mvp_king__2','Double roi des HDM','2 titres','⭐','joueur','palmares','tier',true,'title_mvp_king',2,167),
('title_mvp_king__3','Triple couronne des HDM','3 titres','⭐','joueur','palmares','tier',true,'title_mvp_king',3,168),
('title_mvp_king__4','Quadruple roi des HDM','4 titres','⭐','joueur','palmares','tier',true,'title_mvp_king',4,169),
('title_mvp_king__5','Empereur des HDM','5 titres','⭐','joueur','palmares','tier',true,'title_mvp_king',5,170),
('title_best_winrate__1','Meilleur taux de victoire','1 titre','📈','joueur','palmares','tier',true,'title_best_winrate',1,171),
('title_best_winrate__2','Double référence','2 titres','📈','joueur','palmares','tier',true,'title_best_winrate',2,172),
('title_best_winrate__3','Maître du taux de victoire','3 titres','📈','joueur','palmares','tier',true,'title_best_winrate',3,173),
('title_best_winrate__4','Quadruple référence','4 titres','📈','joueur','palmares','tier',true,'title_best_winrate',4,174),
('title_best_winrate__5','Domination générationnelle','5 titres','📈','joueur','palmares','tier',true,'title_best_winrate',5,175),
('title_worst_winrate__1','Pire taux de victoire','1 titre','🐈','joueur','palmares','tier',true,'title_worst_winrate',1,176),
('title_worst_winrate__2','Double mauvais sort','2 titres','🐈','joueur','palmares','tier',true,'title_worst_winrate',2,177),
('title_worst_winrate__3','Maudit de la victoire','3 titres','🐈','joueur','palmares','tier',true,'title_worst_winrate',3,178),
('title_worst_winrate__4','Quadruple mauvais sort','4 titres','🐈','joueur','palmares','tier',true,'title_worst_winrate',4,179),
('title_worst_winrate__5','Chat noir éternel','5 titres','🐈','joueur','palmares','tier',true,'title_worst_winrate',5,180),
('title_best_pred_match__1','Meilleur pronostiqueur match','1 titre','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_match',1,181),
('title_best_pred_match__2','Double champion des pronos match','2 titres','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_match',2,182),
('title_best_pred_match__3','Triple champion des pronos match','3 titres','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_match',3,183),
('title_best_pred_match__4','Quadruple champion des pronos match','4 titres','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_match',4,184),
('title_best_pred_match__5','Dynastie des pronos match','5 titres','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_match',5,185),
('title_worst_pred_match__1','Pire pronostiqueur match','1 titre','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_match',1,186),
('title_worst_pred_match__2','Double lanterne des pronos match','2 titres','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_match',2,187),
('title_worst_pred_match__3','Triple lanterne des pronos match','3 titres','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_match',3,188),
('title_worst_pred_match__4','Quadruple lanterne des pronos match','4 titres','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_match',4,189),
('title_worst_pred_match__5','Abonné à la dernière place match','5 titres','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_match',5,190),
('title_best_pred_player__1','Meilleur pronostiqueur joueur','1 titre','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_player',1,191),
('title_best_pred_player__2','Double champion des pronos joueurs','2 titres','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_player',2,192),
('title_best_pred_player__3','Triple champion des pronos joueurs','3 titres','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_player',3,193),
('title_best_pred_player__4','Quadruple champion des pronos joueurs','4 titres','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_player',4,194),
('title_best_pred_player__5','Dynastie des pronos joueurs','5 titres','🔮','pronostiqueur','palmares','tier',true,'title_best_pred_player',5,195),
('title_worst_pred_player__1','Pire pronostiqueur joueur','1 titre','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_player',1,196),
('title_worst_pred_player__2','Double lanterne des pronos joueurs','2 titres','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_player',2,197),
('title_worst_pred_player__3','Triple lanterne des pronos joueurs','3 titres','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_player',3,198),
('title_worst_pred_player__4','Quadruple lanterne des pronos joueurs','4 titres','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_player',4,199),
('title_worst_pred_player__5','Abonné à la dernière place joueurs','5 titres','📉','pronostiqueur','palmares','tier',true,'title_worst_pred_player',5,200),
('title_best_pred_overall__1','Meilleur pronostiqueur cumulé','1 titre','🏅','pronostiqueur','palmares','tier',true,'title_best_pred_overall',1,201),
('title_best_pred_overall__2','Double champion cumulé','2 titres','🏅','pronostiqueur','palmares','tier',true,'title_best_pred_overall',2,202),
('title_best_pred_overall__3','Triple champion cumulé','3 titres','🏅','pronostiqueur','palmares','tier',true,'title_best_pred_overall',3,203),
('title_best_pred_overall__4','Quadruple champion cumulé','4 titres','🏅','pronostiqueur','palmares','tier',true,'title_best_pred_overall',4,204),
('title_best_pred_overall__5','Dynastie des pronos','5 titres','🏅','pronostiqueur','palmares','tier',true,'title_best_pred_overall',5,205),
('title_second_overall__1','Deuxième pronostiqueur cumulé','1 titre','🥈','pronostiqueur','palmares','tier',true,'title_second_overall',1,206),
('title_second_overall__2','Double dauphin','2 titres','🥈','pronostiqueur','palmares','tier',true,'title_second_overall',2,207),
('title_second_overall__3','Triple dauphin','3 titres','🥈','pronostiqueur','palmares','tier',true,'title_second_overall',3,208),
('title_second_overall__4','Quadruple dauphin','4 titres','🥈','pronostiqueur','palmares','tier',true,'title_second_overall',4,209),
('title_second_overall__5','Éternel deuxième','5 titres','🥈','pronostiqueur','palmares','tier',true,'title_second_overall',5,210),
('title_third_overall__1','Troisième pronostiqueur cumulé','1 titre','🥉','pronostiqueur','palmares','tier',true,'title_third_overall',1,211),
('title_third_overall__2','Double troisième','2 titres','🥉','pronostiqueur','palmares','tier',true,'title_third_overall',2,212),
('title_third_overall__3','Triple troisième','3 titres','🥉','pronostiqueur','palmares','tier',true,'title_third_overall',3,213),
('title_third_overall__4','Quadruple troisième','4 titres','🥉','pronostiqueur','palmares','tier',true,'title_third_overall',4,214),
('title_third_overall__5','Abonné au podium','5 titres','🥉','pronostiqueur','palmares','tier',true,'title_third_overall',5,215),
('title_last_overall__1','Pire pronostiqueur cumulé','1 titre','🪫','pronostiqueur','palmares','tier',true,'title_last_overall',1,216),
('title_last_overall__2','Double dernier cumulé','2 titres','🪫','pronostiqueur','palmares','tier',true,'title_last_overall',2,217),
('title_last_overall__3','Triple dernier cumulé','3 titres','🪫','pronostiqueur','palmares','tier',true,'title_last_overall',3,218),
('title_last_overall__4','Quadruple dernier cumulé','4 titres','🪫','pronostiqueur','palmares','tier',true,'title_last_overall',4,219),
('title_last_overall__5','Lanterne éternelle','5 titres','🪫','pronostiqueur','palmares','tier',true,'title_last_overall',5,220);
create or replace function public.recalculate_profile_badges(p_profile_id uuid)
returns void language plpgsql security definer set search_path to 'public'
as $fn$ begin return; end; $fn$;

create or replace function public.recalculate_all_badges()
returns void language plpgsql security definer set search_path to 'public'
as $fn$ begin return; end; $fn$;

create or replace function public.award_season_titles(p_season_id uuid)
returns void language plpgsql security definer set search_path to 'public'
as $fn$ begin return; end; $fn$;
