-- Optional sports-management module: availability opening and reminder notifications.
-- Additive and inert while private.app_feature_flags.sports_management is false.

alter table public.push_delivery_log
  drop constraint if exists push_delivery_log_kind_check;

alter table public.push_delivery_log
  add constraint push_delivery_log_kind_check check (
    kind in (
      'new_match',
      'closing_soon',
      'result_validated',
      'availability_open',
      'availability_j3',
      'availability_j1',
      'availability_manual'
    )
  );

create table public.sport_availability_notification_events (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.match_sport_workflows(match_id) on delete restrict,
  participant_id uuid not null,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  kind text not null check (
    kind in (
      'availability_open',
      'availability_j3',
      'availability_j1',
      'availability_manual'
    )
  ),
  source text not null check (source in ('automatic', 'manual')),
  scheduled_for timestamptz not null,
  requested_at timestamptz not null default now(),
  requested_by uuid references public.profiles(id) on delete set null,
  reason text check (reason is null or char_length(reason) <= 500),
  dispatch_status text not null default 'pending' check (
    dispatch_status in (
      'pending',
      'dispatch_requested',
      'completed',
      'no_subscription',
      'dispatch_failed'
    )
  ),
  dispatch_requested_at timestamptz,
  delivery_completed_at timestamptz,
  network_request_id bigint,
  attempted_count integer not null default 0 check (attempted_count >= 0),
  sent_count integer not null default 0 check (sent_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  created_at timestamptz not null default now(),
  foreign key (participant_id, match_id)
    references public.match_sport_participants(id, match_id) on delete restrict,
  check (
    (source = 'manual' and kind = 'availability_manual')
    or (source = 'automatic' and kind <> 'availability_manual')
  )
);

comment on table public.sport_availability_notification_events is
  'Per-player history and outbox for availability opening and reminder pushes.';

create unique index sport_availability_notification_auto_once_idx
  on public.sport_availability_notification_events(participant_id, kind)
  where source = 'automatic';

create index sport_availability_notification_match_timeline_idx
  on public.sport_availability_notification_events(match_id, requested_at desc);

create index sport_availability_notification_profile_timeline_idx
  on public.sport_availability_notification_events(profile_id, requested_at desc);

alter table public.sport_availability_notification_events enable row level security;
revoke all on table public.sport_availability_notification_events
  from public, anon, authenticated;
revoke all on sequence public.sport_availability_notification_events_id_seq
  from public, anon, authenticated;
grant select, insert, update on table public.sport_availability_notification_events
  to service_role;
grant usage, select on sequence public.sport_availability_notification_events_id_seq
  to service_role;

create or replace function public.internal_sport_push_dispatch(
  p_kind text,
  p_match_id uuid,
  p_profile_ids uuid[]
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_match record;
  v_payload jsonb;
  v_subscriptions jsonb;
begin
  if p_kind not in (
    'availability_open',
    'availability_j3',
    'availability_j1',
    'availability_manual'
  ) then
    raise exception 'Unknown sports notification kind' using errcode = '22023';
  end if;

  if p_profile_ids is null or cardinality(p_profile_ids) = 0 then
    return jsonb_build_object(
      'payload', '{}'::jsonb,
      'subscriptions', '[]'::jsonb
    );
  end if;

  select
    m.id,
    m.kickoff_at,
    o.name as opponent_name
  into v_match
  from public.matches m
  join public.opponents o on o.id = m.opponent_id
  where m.id = p_match_id;

  if not found then
    raise exception 'Match not found' using errcode = 'P0002';
  end if;

  v_payload := case p_kind
    when 'availability_open' then jsonb_build_object(
      'title', 'Disponibilités ouvertes',
      'body', format(
        'AS Grinta – %s le %s. Indique si tu es disponible ou absent.',
        v_match.opponent_name,
        to_char(v_match.kickoff_at at time zone 'Europe/Paris', 'DD/MM à HH24hMI')
      ),
      'url', '.',
      'tag', 'sport-' || p_match_id || '-availability-open'
    )
    when 'availability_j3' then jsonb_build_object(
      'title', 'Réponds pour le prochain match',
      'body', format(
        'AS Grinta – %s : tu n’as pas encore indiqué ta disponibilité.',
        v_match.opponent_name
      ),
      'url', '.',
      'tag', 'sport-' || p_match_id || '-availability-j3'
    )
    when 'availability_j1' then jsonb_build_object(
      'title', 'Dernier rappel disponibilité',
      'body', format(
        'AS Grinta – %s joue demain. Disponible ou absent ?',
        v_match.opponent_name
      ),
      'url', '.',
      'tag', 'sport-' || p_match_id || '-availability-j1'
    )
    else jsonb_build_object(
      'title', 'Le staff attend ta réponse',
      'body', format(
        'AS Grinta – %s : indique maintenant si tu es disponible ou absent.',
        v_match.opponent_name
      ),
      'url', '.',
      'tag', 'sport-' || p_match_id || '-availability-manual'
    )
  end;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'profile_id', subscription.profile_id,
        'endpoint', subscription.endpoint,
        'p256dh', subscription.p256dh,
        'auth', subscription.auth
      )
    ),
    '[]'::jsonb
  )
  into v_subscriptions
  from public.push_subscriptions subscription
  join public.profiles profile on profile.id = subscription.profile_id
  where subscription.profile_id = any(p_profile_ids)
    and profile.status = 'active'
    and profile.notify_match_reminders
    and exists (
      select 1
      from public.match_sport_participants participant
      join public.season_players player on player.id = participant.season_player_id
      where participant.match_id = p_match_id
        and participant.is_eligible
        and player.profile_id = subscription.profile_id
        and (
          p_kind = 'availability_open'
          or participant.availability_status = 'no_response'
        )
    );

  return jsonb_build_object(
    'payload', v_payload,
    'subscriptions', v_subscriptions
  );
end;
$function$;

revoke all on function public.internal_sport_push_dispatch(text, uuid, uuid[])
  from public, anon, authenticated;
grant execute on function public.internal_sport_push_dispatch(text, uuid, uuid[])
  to service_role;

create or replace function public.internal_mark_sport_notification_delivery(
  p_event_id bigint,
  p_attempted integer,
  p_sent integer,
  p_failed integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
begin
  update public.sport_availability_notification_events
  set attempted_count = greatest(coalesce(p_attempted, 0), 0),
      sent_count = greatest(coalesce(p_sent, 0), 0),
      failed_count = greatest(coalesce(p_failed, 0), 0),
      dispatch_status = case
        when greatest(coalesce(p_attempted, 0), 0) = 0 then 'no_subscription'
        else 'completed'
      end,
      delivery_completed_at = now()
  where id = p_event_id;

  return found;
end;
$function$;

revoke all on function public.internal_mark_sport_notification_delivery(bigint, integer, integer, integer)
  from public, anon, authenticated;
grant execute on function public.internal_mark_sport_notification_delivery(bigint, integer, integer, integer)
  to service_role;

create or replace function private.dispatch_sport_notification_event(p_event_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_event record;
  v_token text;
  v_request_id bigint;
begin
  select event.id, event.kind, event.match_id, event.profile_id
  into v_event
  from public.sport_availability_notification_events event
  where event.id = p_event_id
  for update;

  if not found then
    return false;
  end if;

  if v_event.id is null then
    return false;
  end if;

  select secret.decrypted_secret
  into v_token
  from vault.decrypted_secrets secret
  where secret.name = 'push_internal_token';

  if v_token is null then
    update public.sport_availability_notification_events
    set dispatch_status = 'dispatch_failed'
    where id = p_event_id;
    return false;
  end if;

  select net.http_post(
    url := 'https://ovzijmqrnsgcmryinkfa.supabase.co/functions/v1/send-push',
    body := jsonb_build_object(
      'kind', v_event.kind,
      'match_id', v_event.match_id,
      'profile_ids', jsonb_build_array(v_event.profile_id),
      'notification_event_id', v_event.id
    ),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-push-token', v_token
    ),
    timeout_milliseconds := 10000
  ) into v_request_id;

  update public.sport_availability_notification_events
  set dispatch_status = 'dispatch_requested',
      dispatch_requested_at = now(),
      network_request_id = v_request_id
  where id = p_event_id;

  return true;
exception
  when others then
    update public.sport_availability_notification_events
    set dispatch_status = 'dispatch_failed'
    where id = p_event_id;
    return false;
end;
$function$;

revoke all on function private.dispatch_sport_notification_event(bigint)
  from public, anon, authenticated;

create or replace function private.create_sport_availability_notification(
  p_match_id uuid,
  p_participant_id uuid,
  p_profile_id uuid,
  p_kind text,
  p_source text,
  p_scheduled_for timestamptz,
  p_requested_by uuid,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_event_id bigint;
begin
  insert into public.sport_availability_notification_events (
    match_id,
    participant_id,
    profile_id,
    kind,
    source,
    scheduled_for,
    requested_by,
    reason
  ) values (
    p_match_id,
    p_participant_id,
    p_profile_id,
    p_kind,
    p_source,
    p_scheduled_for,
    p_requested_by,
    nullif(trim(p_reason), '')
  )
  on conflict do nothing
  returning id into v_event_id;

  if v_event_id is not null then
    perform private.dispatch_sport_notification_event(v_event_id);
  end if;

  return v_event_id;
end;
$function$;

revoke all on function private.create_sport_availability_notification(uuid, uuid, uuid, text, text, timestamptz, uuid, text)
  from public, anon, authenticated;

create or replace function private.process_sport_availability_notifications(
  p_now timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_row record;
  v_kind text;
  v_scheduled_for timestamptz;
  v_event_id bigint;
  v_opened integer := 0;
  v_closed integer := 0;
  v_created integer := 0;
begin
  if not private.is_feature_enabled('sports_management') then
    return jsonb_build_object(
      'opened_workflows', 0,
      'closed_workflows', 0,
      'notifications_created', 0
    );
  end if;

  with opened as (
    update public.match_sport_workflows workflow
    set availability_state = 'open',
        availability_opened_at = coalesce(workflow.availability_opened_at, p_now),
        updated_at = p_now
    from public.matches match
    where match.id = workflow.match_id
      and match.status = 'a_venir'
      and match.kickoff_at > p_now
      and workflow.availability_state = 'pending'
      and workflow.availability_opens_at <= p_now
    returning workflow.match_id
  )
  select count(*)::integer into v_opened from opened;

  with closed as (
    update public.match_sport_workflows workflow
    set availability_state = 'closed',
        updated_at = p_now
    from public.matches match
    where match.id = workflow.match_id
      and workflow.availability_state <> 'closed'
      and (match.status <> 'a_venir' or match.kickoff_at <= p_now)
    returning workflow.match_id
  )
  select count(*)::integer into v_closed from closed;

  for v_row in
    select
      workflow.match_id,
      workflow.availability_opens_at,
      participant.id as participant_id,
      participant.availability_status,
      player.profile_id,
      match.kickoff_at
    from public.match_sport_workflows workflow
    join public.matches match on match.id = workflow.match_id
    join public.match_sport_participants participant
      on participant.match_id = workflow.match_id
    join public.season_players player on player.id = participant.season_player_id
    join public.profiles profile on profile.id = player.profile_id
    where workflow.availability_state = 'open'
      and match.status = 'a_venir'
      and match.kickoff_at > p_now
      and participant.is_eligible
      and player.profile_id is not null
      and profile.status = 'active'
    order by match.kickoff_at, participant.id
  loop
    v_kind := null;
    v_scheduled_for := null;

    if not exists (
      select 1
      from public.sport_availability_notification_events event
      where event.participant_id = v_row.participant_id
        and event.kind = 'availability_open'
        and event.source = 'automatic'
    ) then
      v_kind := 'availability_open';
      v_scheduled_for := v_row.availability_opens_at;
    elsif v_row.availability_status = 'no_response'
      and p_now >= v_row.kickoff_at - interval '24 hours'
      and not exists (
        select 1
        from public.sport_availability_notification_events event
        where event.participant_id = v_row.participant_id
          and event.kind = 'availability_j1'
          and event.source = 'automatic'
      ) then
      v_kind := 'availability_j1';
      v_scheduled_for := v_row.kickoff_at - interval '24 hours';
    elsif v_row.availability_status = 'no_response'
      and p_now >= v_row.kickoff_at - interval '72 hours'
      and p_now < v_row.kickoff_at - interval '24 hours'
      and not exists (
        select 1
        from public.sport_availability_notification_events event
        where event.participant_id = v_row.participant_id
          and event.kind = 'availability_j3'
          and event.source = 'automatic'
      ) then
      v_kind := 'availability_j3';
      v_scheduled_for := v_row.kickoff_at - interval '72 hours';
    end if;

    if v_kind is not null then
      v_event_id := private.create_sport_availability_notification(
        v_row.match_id,
        v_row.participant_id,
        v_row.profile_id,
        v_kind,
        'automatic',
        v_scheduled_for,
        null,
        null
      );
      if v_event_id is not null then
        v_created := v_created + 1;
      end if;
    end if;
  end loop;

  return jsonb_build_object(
    'opened_workflows', v_opened,
    'closed_workflows', v_closed,
    'notifications_created', v_created
  );
end;
$function$;

revoke all on function private.process_sport_availability_notifications(timestamptz)
  from public, anon, authenticated;
grant execute on function private.process_sport_availability_notifications(timestamptz)
  to service_role;

create or replace function private.send_sport_availability_reminder(
  p_match_id uuid,
  p_season_player_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor uuid := (select auth.uid());
  v_row record;
  v_event_id bigint;
  v_created integer := 0;
  v_skipped_recent integer := 0;
  v_target_count integer := 0;
  v_reason text := nullif(trim(p_reason), '');
begin
  perform private.require_sports_management_enabled();
  if not private.is_admin() then
    raise exception 'Active administrator role required' using errcode = '42501';
  end if;
  if p_match_id is null then
    raise exception 'Match id is required' using errcode = '22023';
  end if;
  if v_reason is not null and char_length(v_reason) > 500 then
    raise exception 'Reason is too long' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.match_sport_workflows workflow
    join public.matches match on match.id = workflow.match_id
    where workflow.match_id = p_match_id
      and workflow.availability_state = 'open'
      and match.status = 'a_venir'
      and match.kickoff_at > now()
  ) then
    raise exception 'Availability reminders are not open for this match'
      using errcode = '22023';
  end if;

  for v_row in
    select
      participant.id as participant_id,
      participant.season_player_id,
      player.profile_id
    from public.match_sport_participants participant
    join public.season_players player on player.id = participant.season_player_id
    join public.profiles profile on profile.id = player.profile_id
    where participant.match_id = p_match_id
      and participant.is_eligible
      and participant.availability_status = 'no_response'
      and player.profile_id is not null
      and profile.status = 'active'
      and (
        p_season_player_id is null
        or participant.season_player_id = p_season_player_id
      )
    order by participant.id
  loop
    v_target_count := v_target_count + 1;

    if exists (
      select 1
      from public.sport_availability_notification_events event
      where event.participant_id = v_row.participant_id
        and event.kind = 'availability_manual'
        and event.requested_at > now() - interval '10 minutes'
    ) then
      v_skipped_recent := v_skipped_recent + 1;
      continue;
    end if;

    v_event_id := private.create_sport_availability_notification(
      p_match_id,
      v_row.participant_id,
      v_row.profile_id,
      'availability_manual',
      'manual',
      now(),
      v_actor,
      v_reason
    );

    if v_event_id is not null then
      v_created := v_created + 1;
    end if;
  end loop;

  if p_season_player_id is not null and v_target_count = 0 then
    raise exception 'Player is not waiting for an availability response'
      using errcode = '22023';
  end if;

  insert into private.sport_admin_audit_log (
    match_id,
    action,
    actor_profile_id,
    reason,
    metadata
  ) values (
    p_match_id,
    'send_availability_reminder',
    v_actor,
    v_reason,
    jsonb_build_object(
      'season_player_id', p_season_player_id,
      'target_count', v_target_count,
      'created_count', v_created,
      'skipped_recent_count', v_skipped_recent
    )
  );

  return jsonb_build_object(
    'target_count', v_target_count,
    'created_count', v_created,
    'skipped_recent_count', v_skipped_recent
  );
end;
$function$;

revoke all on function private.send_sport_availability_reminder(uuid, uuid, text)
  from public, anon, authenticated;

create or replace function private.get_sport_availability_reminder_summary(
  p_match_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_result jsonb;
begin
  perform private.require_sports_management_enabled();
  if not private.is_admin() then
    raise exception 'Active administrator role required' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'match_id', workflow.match_id,
    'availability_state', workflow.availability_state,
    'no_response_count', (
      select count(*)
      from public.match_sport_participants participant
      where participant.match_id = workflow.match_id
        and participant.is_eligible
        and participant.availability_status = 'no_response'
    ),
    'open_sent_count', (
      select count(*)
      from public.sport_availability_notification_events event
      where event.match_id = workflow.match_id
        and event.kind = 'availability_open'
    ),
    'j3_sent_count', (
      select count(*)
      from public.sport_availability_notification_events event
      where event.match_id = workflow.match_id
        and event.kind = 'availability_j3'
    ),
    'j1_sent_count', (
      select count(*)
      from public.sport_availability_notification_events event
      where event.match_id = workflow.match_id
        and event.kind = 'availability_j1'
    ),
    'last_manual_at', (
      select max(event.requested_at)
      from public.sport_availability_notification_events event
      where event.match_id = workflow.match_id
        and event.kind = 'availability_manual'
    ),
    'can_remind', workflow.availability_state = 'open'
      and match.status = 'a_venir'
      and match.kickoff_at > now(),
    'players', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'season_player_id', participant.season_player_id,
          'last_reminder_at', reminder.last_reminder_at,
          'manual_cooldown_until', reminder.last_manual_at + interval '10 minutes'
        ) order by participant.season_player_id
      )
      from public.match_sport_participants participant
      left join lateral (
        select
          max(event.requested_at) as last_reminder_at,
          max(event.requested_at) filter (
            where event.kind = 'availability_manual'
          ) as last_manual_at
        from public.sport_availability_notification_events event
        where event.participant_id = participant.id
      ) reminder on true
      where participant.match_id = workflow.match_id
        and participant.is_eligible
    ), '[]'::jsonb)
  )
  into v_result
  from public.match_sport_workflows workflow
  join public.matches match on match.id = workflow.match_id
  where workflow.match_id = p_match_id;

  if v_result is null then
    raise exception 'Sports workflow not found' using errcode = 'P0002';
  end if;

  return v_result;
end;
$function$;

revoke all on function private.get_sport_availability_reminder_summary(uuid)
  from public, anon, authenticated;

create or replace function public.admin_send_match_availability_reminder(
  p_match_id uuid,
  p_season_player_id uuid default null,
  p_reason text default null
)
returns jsonb
language sql
security invoker
set search_path = ''
as $function$
  select private.send_sport_availability_reminder(
    p_match_id,
    p_season_player_id,
    p_reason
  );
$function$;

create or replace function public.admin_get_match_availability_reminders(
  p_match_id uuid
)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $function$
  select private.get_sport_availability_reminder_summary(p_match_id);
$function$;

revoke all on function public.admin_send_match_availability_reminder(uuid, uuid, text)
  from public, anon;
revoke all on function public.admin_get_match_availability_reminders(uuid)
  from public, anon;
grant execute on function public.admin_send_match_availability_reminder(uuid, uuid, text)
  to authenticated;
grant execute on function public.admin_get_match_availability_reminders(uuid)
  to authenticated;

select cron.schedule(
  'sports-availability-reminders',
  '* * * * *',
  $$select private.process_sport_availability_notifications(now());$$
);
